### ISSUE TITLE
59121c69531795788deb4788b747f4ec71183983  caused significant performance regression

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#1037]
See May 9th: https://circt.org/perf/

**Comment by seldridge** [comment]
I was a bit too quick with closing this. This issue is pointing at a possibly different performance regression. I'll re-open until we have clarification that this is fixed.

**Comment by fabianschuiki** [comment]
Seems fixed now: https://circt.org/perf/

**Comment by seldridge** [comment]
And for the record, this was a regression I introduced in b24fca0b53b28d702b8eb73e19641f0908e89271. I think 59121c69531795788deb4788b747f4ec71183983 was a-okay. :+1:
