### ISSUE TITLE
[firrtl] Flow checking rejects firrtl/regress/Rob.fir

### ISSUE THREAD

**Issue by lattner** [llvm/circt#1058]
I'm not sure if this is correct or not, but we're currently rejecting this testcase from the firrtl regression suite with:

```
rob.scala:934:41: error: 'firrtl.partialconnect' op has invalid flow: the left-hand-side has source flow (expected sink or duplex flow).
rob.scala:934:41: note: see current operation: "firrtl.partialconnect"(%T_23566, %T_23562) : (!firrtl.uint<37>, !firrtl.uint<40>) -> ()
regress/Rob.fir:46:9: note: the left-hand-side was defined here.
        infer mport T_23566 = T_23558[T_23565], clk
        ^
```

@seldridge

**Comment by seldridge** [comment]
I think the default flow is "source" and flow computation is incorrectly using the default case for `mport` (`mport` isn't handled at all). Should be a quick fix. 

Thanks for finding and reporting this.
