### ISSUE TITLE
Check our handling of `dshlw`

### ISSUE THREAD

**Issue by lattner** [llvm/circt#1062]
We're currently lowering `dshlw` to shift right.  Is this correct?  It seems like it should be a shift left.  That said, the semantics are not documented, so I'm not clear about this.  In LowerToHW.cpp:

```
  LogicalResult visitExpr(DShlwPrimOp op) {
    return lowerDivLikeOp<comb::ShrSOp, comb::ShrUOp>(op);
  }
```

**Comment by hanchenye** [comment]
Fixed in #1081
