### ISSUE TITLE
Add README section explaining how to use Python bindings

### ISSUE THREAD

**Issue by fabianschuiki** [llvm/circt#1072]
It would be great if the README file had a section which briefly explained the necessary steps to get the Python bindings up and running for a user that is mainly interested in using CIRCT through Python, rather than the C/C++ API and tools.

**Comment by lattner** [comment]
I'd recommend adding this to its own `docs/PythonBindings.md` file and link to that from the readme.

**Comment by fabianschuiki** [comment]
Done!
