### ISSUE TITLE
[FIRRTL] missing folders for constant/constant Xor and friends

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#1130]

**Comment by lattner** [comment]
What is this bug?  The title isn't enough to understand what is going on here.

**Comment by darthscsi** [comment]
Firrtl is missing constant folders for most binary operations.

**Comment by lattner** [comment]
No it isn't.  I implemented them all.  They are in the fold() hooks.

**Comment by darthscsi** [comment]
tracked in #1131
