### ISSUE TITLE
Python format check (and formatting) are broken

### ISSUE THREAD

**Issue by mikeurbach** [llvm/circt#1162]
See, for example, https://github.com/llvm/circt/runs/2661287840#step:15:9.

Seems this has been the case since we switched to a Docker image for the PR gate check.

We should a) fix the check to enforce consistent formatting, and b) run `yapf -i -r .` from the root of the repo to clean up the discrepancies that have slipped in.

**Comment by teqdruid** [comment]
I think this is just a matter of installing the `toml` package in the docker container.

**Comment by mikeurbach** [comment]
FYI I'm working on this.

**Comment by teqdruid** [comment]
Thanks!
