### ISSUE TITLE
FIRRTL Error involving Division Fold

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#1187]
The following circuit crashes `firtool`. 

```scala
circuit Foo:
  module Foo:
    input divisor: UInt<1>
    output result: UInt<0>

    wire dividend: UInt<0>
    dividend is invalid

    result <= div(dividend, divisor)
```

The issue is that `div(x, invalid)` or `div(invalid, x)` is trying to fold to `UInt<$width>(0)` where `$width` is the result type. This is the usual problem where `APInt` can't have a zero width.

This started to show up on `circt/perf`'s test1 because inter-module constant propagation got turned on in e73115d5969905b2def85af062d3feb15c204003 which tickles this for test1. The minimal circuit above hits the same code path but goes through the `SimpleCanonicalizer` which means that this will fail even without/before e73115d5969905b2def85af062d3feb15c204003.

**Comment by lattner** [comment]
Fixed in 99ce0d32, thanks!
