### ISSUE TITLE
[FIRRTL] Rename `BlackBoxReader.cpp` or `BlackboxMemory.cpp`

### ISSUE THREAD

**Issue by lattner** [llvm/circt#1209]
We should have a consistent casing strategy here, who wins?

**Comment by youngar** [comment]
I think "Black Box" makes more sense, and is consistent with annotation names.

**Comment by lattner** [comment]
That's a good argument

**Comment by seldridge** [comment]
Chisel and FIRRTL have always used `BlackBox` or `blackBox` (implying it's two words). Wikipedia seems to agree: https://en.wikipedia.org/wiki/Black_box. However, adjectives or nouns derived from this concept go different ways, e.g., [`black-box testing`](https://en.wikipedia.org/wiki/Black-box_testing) or [`blackboxing`](https://en.wikipedia.org/wiki/Blackboxing).

I'm good with `BlackBox`, but am fine with either.

**Comment by youngar** [comment]
For reference, the pass names are "firrtl-blackbox-reader" and "firrtl-blackbox-memory"

**Comment by lattner** [comment]
It sounds like we should go with `BlackBox` or `blackBox` in camel case situations and `blackbox` in all lower case scenarios.  That's simple and consistent.  Who wants to do the honors?

**Comment by fabianschuiki** [comment]
:tada: this has been bugging me for a while, thanks!

**Comment by youngar** [comment]
closed by #1227
