### ISSUE TITLE
[SV] Add Builder for Twine to VeratimOp

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#1244]
Add a builder to `sv::VerbatimOp` that accepts a Twine argument. This will make it a lot easier to construct strings that need to be passed in without having to do an explicit conversion to a string beforehand.

This was suggested by @youngar in https://github.com/llvm/circt/pull/1170/files#r649805728 (h/t).

**Comment by fabianschuiki** [comment]
There's now a constructor for `StringAttr` in MLIR that takes a `Twine` argument that will be handy for this.

**Comment by lattner** [comment]
Done in 41100f15
