### ISSUE TITLE
FIRRTL dialect annotation support isn't right

### ISSUE THREAD

**Issue by lattner** [llvm/circt#1300]
Various FIRRTL dialect ops have an "annotations" attribute which is a required attribute, but they are declared like this in tblgen: `DefaultValuedAttr<AnnotationArrayAttr, "{}">:$annotations);`

This is a problem: it is a required attribute, but defaults to null.  The pretty printers work around this in various ways, but the generic op printer crashes (and other things will probably be unhappy as well):

`circt-translate -import-firrtl -verify-diagnostics test/Dialect/FIRRTL/parse-basic.fir --mlir-print-op-generic`

I think we should move to the design where these are required and empty if not present (we should just change all the build methods to create an empty array with `$ctx`.

One other oddity is that the Module ops don't elide printing the annotations array when empty.

When this is fixed, some defensive null checking code in this patch can be removed: https://github.com/llvm/circt/commit/e8065e6f3c30dc2ccaceadb2fcc31ed0fde1c485

**Comment by lattner** [comment]
A complexity here is that default initializers don't get rewritten and can't have $_ctx or $_builder in them.

**Comment by lattner** [comment]
Progress: 6ec64886

**Comment by lattner** [comment]
Finished in b2f4db87

**Comment by seldridge** [comment]
Thanks for cleaning up my code! This looks _way_ better after your patch series.
