### ISSUE TITLE
[Speaker for Wednesday Meeting] Open Road

### ISSUE THREAD

**Issue by stevenmburns** [llvm/circt#1322]
@lattner I contacted Andrew Kahng and he is willing to give an overview of [OpenRoad](https://theopenroadproject.org/) to the Wednesday 11am meeting. July 7th or 14th will work. I don't have access to the agenda doc or I would have added a note there.

**Comment by lattner** [comment]
Fantastic, thank you for arranging this!  I added him to the schedule for July 7, thanks!

**Comment by stevenmburns** [comment]
I contacted Andrew with the date and zoom address.

**Comment by lattner** [comment]
Thank you Steve!
