### ISSUE TITLE
[FIRRTL] Canonicalize tail/head/bits to bits, collapse nested bits

### ISSUE THREAD

**Issue by fabianschuiki** [llvm/circt#1326]
Canonicalize tail/head/bits operations to a simple bits operation (optional). Then collapse nested bit extraction operations into one. E.g., `tail(tail(x, 1), 3) = tail(x, 4)`, or `bits(bits(x, 3, 1), 1, 0) = bits(x, 2, 1)` (these need double-checking :wink:).

**Comment by lattner** [comment]
Why not do this on comb?

**Comment by fabianschuiki** [comment]
@lattner Yeah excellent point, that makes much more sense. Thanks @fyquah for tackling this there!
