### ISSUE TITLE
[FIRRTL] Verify Zero-width Behavior

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#1350]
It's unclear to me if CIRCT is aligning with Scala FIRRTL Compiler zero width behavior as defined in: 
- https://github.com/chipsalliance/firrtl/blob/master/src/test/scala/firrtlTests/ZeroWidthTests.scala

Verify that CIRCT is doing the right thing here, expand this issue with any differences that may exist, and close this once CIRCT passes all these tests.

- [x] Port
- [x] Add
- [x] Mux: https://github.com/llvm/circt/pull/1349
- [ ] ???

**Comment by lattner** [comment]
Nice, thank for tracking this.  Do you have a known ??? after mux?  If not, I'd recommend closing this issue when mux lands, then file new issues for any specific cases that come up, thanks!

**Comment by seldridge** [comment]
> Do you have a known ??? after mux?

That was as far as I got with adding the tests from `ZeroWidthTests.scala`. 

> If not, I'd recommend closing this issue when mux lands, then file new issues for any specific cases that come up, thanks!

I'll just close this when #1349 goes in and open new issues as needed.

**Comment by seldridge** [comment]
Closed the mux issue in #1349. Will re-open new issues as I pull failing tests out of the SFC for zero-width behavior.
