### ISSUE TITLE
[CI] Use the latest clang-format version

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#1417]
Since we use a [docker-based image](https://github.com/circt/images/tree/trunk/circt-ci-build), this should be as easy as modifying the Dockerfile to install the latest clang-format version then updating the workflow in this repo to use it.

https://llvm.discourse.group/t/clang-format-version/3844/5

**Comment by youngar** [comment]
I think [this](https://github.com/google/llvm-premerge-checks/blob/main/containers/base-debian/Dockerfile#L16) is the dockerfile for the LLVM phabricator pre-merge builds.  They install and use the latest release of `clang` as well as `clang-format`.  Would it make sense to follow suit, or do we prefer to mix the `clang` and `clang-format` versions?

**Comment by teqdruid** [comment]
I don't have a preference. We should probably do what MLIR does.

**Comment by youngar** [comment]
Opened a PR here: https://github.com/circt/images/pull/8

**Comment by youngar** [comment]
image updated here: https://github.com/llvm/circt/commit/e16c134c035cb73f47bf311ac318ec21a8a1839a
