### ISSUE TITLE
[PyCDE] Create pipeline to create and publish python wheel

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#1509]
Consider using https://cibuildwheel.readthedocs.io/en/stable/

Use npcomp as an example: https://github.com/llvm/mlir-npcomp/pull/256/files

**Comment by teqdruid** [comment]
We did this internally so as to use faster build agents and pypi auth issues.

**Comment by hovind** [comment]
@teqdruid The `pycde` wheel hasn't been updated since Sep 22, 2023. Could we re-open this issue?

I imagine that the `pypi` auth issues have been sorted out given that wheels for the `esi-runtime` and python `circt` bindings are being published.

**Comment by teqdruid** [comment]
Actually, it's failing since the pycde project is out of space on pypi and I haven't had the chance to delete old daily wheels.

But now that the pypi thing has been figures out and we can run the builds out of the circt repo on the fast runners, building and publishing out of circt is an option. In fact, it's something I've been meaning to get around to.

**Comment by teqdruid** [comment]
And it's only been failing for the last two weeks or so. I wouldn't be surprised if the last versioned release was back in September though. Look through the pre releases for the nightlies.

**Comment by hovind** [comment]
> And it's only been failing for the last two weeks or so. I wouldn't be surprised if the last versioned release was back in September though. Look through the pre releases for the nightlies.

Ah, there it is, thank you! I'm new to the python ecosystem, apologies for the confusion. Thanks for the quick clarification.
