### ISSUE TITLE
Wrong generated include path for unified builds

### ISSUE THREAD

**Issue by stellaraccident** [llvm/circt#1533]
This: `  set(MLIR_TABLEGEN_OUTPUT_DIR ${CMAKE_BINARY_DIR}/tools/mlir/include)`
Should be: `  set(MLIR_TABLEGEN_OUTPUT_DIR ${LLVM_BINARY_DIR}/tools/mlir/include)`

As-is, this will fail if including circt in a project that itself includes llvm-project (vs llvm being the root project).

**Comment by mikeurbach** [comment]
Thanks @stellaraccident, makes sense to me, and updated in 7f7c30b557ea3c4488a711548a6688d4c713870b
