### ISSUE TITLE
[Calyx] Define a Cell Interface.

### ISSUE THREAD

**Issue by cgyurgyik** [llvm/circt#1597]
A `Cell` compromises of Calyx component instances and primitives.

An `InstanceOp` retrieves its port names and directions from the referenced component. A primitive should define port names and directions, as seen with the RegisterOp: 

https://github.com/llvm/circt/blob/486429901e4f794b5ac5008cfb25d1cda579c592/include/circt/Dialect/Calyx/CalyxPrimitives.td#L33-L40

E.g.

```
/// Op Interface for cells.
def CellInterface : OpInterface<"CellInterface"> {
  let cppNamespace = "::circt::calyx";
  let description = [{
    This is an op interface for Calyx Cells. Cells consist
    of primitives and instances of components.
  }];
  let methods = [
    InterfaceMethod<
      "This returns the port names associated with the cell.",
      "SmallVector<StringRef>", "portNames"
    >
    // Also add interface method for port directions.
  ];
}
```

We can then add `DeclareOpInterfaceMethods<CellInterface>` to the `CalyxCell` class to ensure each `Cell` has the proper methods defined.

Reasoning: This ensures each `Cell` defines a `portNames` and `portDirections` function. These are used for readability, and (eventually) verification (e.g. we should never be trying to drive an output port). 

Once support for this is implemented, the following locations should be refactored:
- [ ] iterating over in- and output ports of a InstaceOp in https://github.com/llvm/circt/blob/main/lib/Dialect/Calyx/CalyxOps.cpp#L95
- [x] verify direction of both destination and source of AssignOp (see: #1661). The destination should be Input, and the source should be Output.
    #1697

**Comment by mikeurbach** [comment]
I can work on this.

**Comment by mikeurbach** [comment]
I introduced the basic interface here: https://github.com/llvm/circt/pull/1695. In that PR, I haven't dealt with the TODOs above yet.

**Comment by mikeurbach** [comment]
I landed the interface, so we can start using it. If anyone else wants to loop back to the TODOs in this issue, feel free, or else I'll tackle them at some point.

**Comment by cgyurgyik** [comment]
I'll take care of the AssignOp verification.

**Comment by cgyurgyik** [comment]
Completed by @mikeurbach in #1695.
