### ISSUE TITLE
Performance Regression (After LLVM Merge?)

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#1700]
There's a pretty comical performance regression that showed up last night. This is suspected to be related to the LLVM merge.

<img width="1639" alt="Screen Shot 2021-09-02 at 12 36 51" src="https://user-images.githubusercontent.com/1018530/131883052-9e116f07-3d58-4c4d-b677-4bf0be8a78ed.png">

See: [circt.org/perf](https://circt.org/perf)

**Comment by lattner** [comment]
Filed here: https://bugs.llvm.org/show_bug.cgi?id=51738

**Comment by lattner** [comment]
Patch here:
https://reviews.llvm.org/D109454

**Comment by lattner** [comment]
Landed in https://reviews.llvm.org/D109454  .  Could someone merge in mainline LLVM to pick this up?

**Comment by seldridge** [comment]
Yeah, I'm on it... Thanks for the fix, @lattner!

**Comment by seldridge** [comment]
This _appears_ to be fixed for me locally. I'm kicking off the process of getting circt.org/perf updated, but that takes a while.  Locally, using a debug build and `-verify-each=false`, I'm getting the following results for `test2` which don't look heinously broken:

```
===-------------------------------------------------------------------------===
                         ... Execution time report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 162.1973 seconds

  ----Wall Time----  ----Name----
   33.9496 ( 20.9%)  FIR Parser
  108.4516 ( 66.9%)  'firrtl.circuit' Pipeline
    8.9351 (  5.5%)    'firrtl.module' Pipeline
    5.1524 (  3.2%)      CSE
    0.0000 (  0.0%)        (A) DominanceInfo
    3.7827 (  2.3%)      LowerCHIRRTL
    0.9324 (  0.6%)    InferWidths
    1.7590 (  1.1%)    InferResets
    0.1164 (  0.1%)      (A) circt::firrtl::InstanceGraph
    3.9889 (  2.5%)    LowerFIRRTLTypes
   56.4167 ( 34.8%)    'firrtl.module' Pipeline
    5.9567 (  3.7%)      ExpandWhens
   50.4600 ( 31.1%)      Canonicalizer
    0.0657 (  0.0%)    Inliner
    5.6653 (  3.5%)    IMConstProp
    0.0917 (  0.1%)      (A) circt::firrtl::InstanceGraph
    0.0000 (  0.0%)    BlackBoxReader
   30.6879 ( 18.9%)    'firrtl.module' Pipeline
   30.6879 ( 18.9%)      Canonicalizer
   19.7794 ( 12.2%)  Print .mlir output
    0.0161 (  0.0%)  Rest
  162.1973 (100.0%)  Total
```

**Comment by lattner** [comment]
Thank you @seldridge !  Yes, this looks inline with expectations.  @drom - when we get verification that the graphs are normal tomorrow, can you please manually expunge the bad datapoints from the graph (otherwise the zoom level is not useful)
