### ISSUE TITLE
[Calyx] Match port order in primitives with native Compiler

### ISSUE THREAD

**Issue by rachitnigam** [llvm/circt#1706]
The order of port definitions for a Calyx primitive needs to match that of the native compiler's primitive library. More context: https://github.com/cucapra/calyx/issues/646

**Comment by cgyurgyik** [comment]
Reference for current port ordering:

https://github.com/cucapra/calyx/blob/098e1a4193a7ae1191344170b44ab9dd882df356/tests/backend/circt/no-guards.expect#L19-L24

**Comment by cgyurgyik** [comment]
Modulo a `clk` port in MemoryOp (addressed in #1720), this is already the case!
