### ISSUE TITLE
[Calyx] Verify certains ports are written or driven together.

### ISSUE THREAD

**Issue by cgyurgyik** [llvm/circt#1712]
A few examples:
- [x] A MemoryOp should only be read/written to if its address ports are driven.
    #1764
- [x] A RegisterOp should only be written to if the `write_en` port is driven.
    #1764
- [x] A binary operation should only be read if both the `lhs` and `rhs` have been driven (similar for unary operation). For this one, it could *technically* be driven in another group, but that would require us to walk the ancestor groups in the control each time we verify. A simpler, more restrictive verification is just ensure that `left` and `right` are driven within the same group.
    #1764

Calyx does this by means of an attribute in [Calyx 623](https://github.com/cucapra/calyx/pull/623). This could be done by means of attribute, but I imagine just having this as an addition to `verifyGroupOp` is fine as well.

**Comment by mortbopet** [comment]
Coincidentally, I should already have the infrastructure for doing this locally (a rewrite of `isPortDrivenByGroup` based on the cell interface).

**Comment by cgyurgyik** [comment]
Going to knock this out. May make some slight changes to `isPortDrivenByGroup`, FYI.
