### ISSUE TITLE
[Calyx] Combinational and non-combinational groups are disjoint.

### ISSUE THREAD

**Issue by cgyurgyik** [llvm/circt#1738]
Another restriction on `comb group` that I might have not mentioned: They cannot appear inside normal control operators like `seq` or `par`. The places where `comb group` and `group` may appear are disjoint.

_Originally posted by @rachitnigam in https://github.com/llvm/circt/pull/1736#r703133972_

**Comment by mortbopet** [comment]
This should be implicitly assured by the various validators and 'parented by' restrictions of the different ops. @cgyurgyik @rachitnigam any thoughts, or should we close the issue as solved by #1736?

**Comment by cgyurgyik** [comment]
> #1736

Makes sense to close it to me.
