### ISSUE TITLE
[FIRRTL] Introduce Semantics Checker Pass

### ISSUE THREAD

**Issue by fabianschuiki** [llvm/circt#1740]
We probably need a pass in the FIRRTL dialect that runs early on to do semantic checking of the input.

As discussed in #1444, we want to validate the user input before things like DCE and IMConstProp have the chance to remove unused things and hide errors. A good place to put this would be after as many non-destructive passes as possible (@seldridge suggests after CSE and CHIRRTL lowering), but before the first instance of DCE/IMConstProp runs.

A first implementation of this pass could check that reset values of async reset registers are constants. This will be pretty non-trivial to do, since we'll want to look through drives, last connect semantics, subaccesses, etc. -- all of which is handled by later passes, but needs to be anticipated in this semantic checker where the passes haven't yet run.

Analysis of combinational loops is likely also a good candidate to merge into this pass.

**Comment by seldridge** [comment]
This pass now effectively exists as `SFCCompat` with features added two this in three major PRs:
- https://github.com/llvm/circt/pull/2287
- https://github.com/llvm/circt/pull/2870
- https://github.com/llvm/circt/pull/3049

This is doing both semantic checking as well as semantic resolving (e.g., applying the default interpretation of invalid). If we have more of a need for this stuff we can move it into this pass. Additionally, this pass can be modified to run earlier in the pass pipeline.
