### ISSUE TITLE
[Calyx] `module` compilation generates multiple redundant `import` statements

### ISSUE THREAD

**Issue by rachitnigam** [llvm/circt#1770]
While compiling `test/Conversion/SCFToCalyx/convert_controlflow.mlir` in the #1630 PR, the generated code adds `import "primitives/std.lib" for each defined `module`. This cannot be parsed by the native Calyx compiler which expects all imports to be at the top of the file and not have redundant imports.

**Comment by cgyurgyik** [comment]
I'm not sure this is a bug. Each module is its own program.

**Comment by rachitnigam** [comment]
Okay, closing this for now in that case.
