### ISSUE TITLE
[ESI] Make instances match module declarations

### ISSUE THREAD

**Issue by lattner** [llvm/circt#1775]
We have a problem where `InstanceOp::verifySymbolUses` is unable to enforce the instances and module declarations line up w.r.t. port names and types.  This is because ESI is (ab)using the lack of checking by using one external declaration and having multiple instances refer to it.  A consequence of this is that [this patch](https://github.com/llvm/circt/commit/8a41c3f326436427a1dc6da792c6cad475c11826) had to land an important patch on the path to parameterized modules.

Please fix ESI so it creates one extern module for each signature it needs.  These can/should have the same "verilogName" attribute so they get emitted as the same declaration, but until the code is structured and verified, I can't make progress with parameterized modules.

Thanks!

**Comment by teqdruid** [comment]
To be fair, this is a new requirement. When this exact issue has come up in the past (IIRC) it was discussed and this was determined to be the way to do it. There's a reason the `InstanceOp` verifier doesn't check types on extern mods.

I'll get on it.

**Comment by lattner** [comment]
I recall we discussed something here, but I don’t recall the details.  Thank you for taking care of this.  The lack of checking is hiding other problems.

**Comment by teqdruid** [comment]
I'm a big fan of static verification, but just figured it'd have to be put off until we had support for parameterized extern modules. Didn't even think of creating one extern mod for each parameterization! This is a far nicer design.

**Comment by lattner** [comment]
> This is a far nicer design.

I wouldn't say that it is "nice", but it is "consistent" with our current parameterization approach.  Thank you for fixing this!
