### ISSUE TITLE
[FIRRTL] `FIRRTLLowering::visitDecl(MemOp op)`  has no tests

### ISSUE THREAD

**Issue by lattner** [llvm/circt#1776]
This code is doing a somewhat fiddly thing with memory modules - creating instances before the referenced module is created.  I need to refactor this code to make progress on parameterized module but the logic has no tests.  Can someone add a test or two so I don't break anything obvious?

**Comment by lattner** [comment]
@darthscsi can you assign this to someone please?  Thanks

**Comment by lattner** [comment]
Specific issue - if you add an abort to the end of this method, no tests fail.

**Comment by lattner** [comment]
@

**Comment by darthscsi** [comment]
hmm, lower-to-hw.mlir:657 should be testing this.  Will look at it.

**Comment by darthscsi** [comment]
When I add an abort to the end of visitDecl, I see it in the test case:
```andrew@narya:~/src/circt/build$ /home/andrew/src/circt/build/bin/circt-opt -lower-firrtl-to-hw /home/andrew/src/circt/test/Conversion/FIRRTLToHW/lower-to-hw.mlir
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Aborted```

I actually see 4 tests fail:
```  CIRCT :: Conversion/FIRRTLToHW/errors.mlir
  CIRCT :: Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
  CIRCT :: Conversion/FIRRTLToHW/lower-to-hw.mlir
  CIRCT :: Dialect/FIRRTL/SFCTests/data-taps.fir```

**Comment by darthscsi** [comment]
Without the abort, tests pass:
```
andrew@narya:~/src/circt/build$ ninja check-circt
[165/166] Running the CIRCT regression tests

Testing Time: 1.49s
  Unsupported      :   2
  Passed           : 258
  Expectedly Failed:   3
  ```

**Comment by lattner** [comment]
You're totally right, sorry for the noise!
