### ISSUE TITLE
[Calyx] [Tracker] Make SCF to Calyx work with native compiler

### ISSUE THREAD

**Issue by rachitnigam** [llvm/circt#1777]
Tracker issue to make code generated by #1630 work with the native compiler. Let's consider this successfully done when we can simulate SCF generated program on Verilator by going through the Calyx native compiler

## CIRCT
- [x] #1769 [1]
- [x] #1630
- [x] #1802 
- [x] #1804
- [x] #1812
- [x] #1813
- [x] #1814
- [x] #1815 
- [x] #1830
- [x] #1831
- [X] #1854
- [x] #1840
- [x]  #1841
- [x] #1846
- [x] #1849
- [x] #1862
- [x] #1863

[1]: Temporary program validation in #1774. This will remove when the native compiler and the Calyx dialect support wires in the source position.

## Calyx

**Comment by mortbopet** [comment]
@cgyurgyik @rachitnigam any final comments on this?

**Comment by cgyurgyik** [comment]
I imagine that we'll run into bugs while lowering to Calyx, but I'm fine opening separate issues for this as well.

**Comment by rachitnigam** [comment]
Yeah, I agree with Chris. Let's ensure that at least the tests in the CIRCT repo compile with the native compiler correctly first and then we can try moving onto bigger examples.

**Comment by rachitnigam** [comment]
Looks like this is done for now so closing it!
