### ISSUE TITLE
[MSFT] [HW] InstanceOp doesn't return error if top-level module is non-existent.

### ISSUE THREAD

**Issue by cgyurgyik** [llvm/circt#1779]
For more context, looking at git blame [here](https://github.com/llvm/circt/commit/3f7ed33578f6068e53ae8a06030af40a1b8136c5#diff-1d225e2b997a8d4507168bd13ef7697369a37fa20aebfb321b8b5ae1e18aa73cR262-R268), it seems this was done initially by @lattner for `hw.instance`.

_Originally posted by @cgyurgyik in https://github.com/llvm/circt/pull/1756#discussion_r705713927_

^ I'm happy to clean this up, but just want to make sure I'm not missing some obvious reason why this exists.

**Comment by teqdruid** [comment]
Sorry, are you referring to `hw.instance` or `msft.instance`?

**Comment by teqdruid** [comment]
Or is it both, and you want to know why this behavior in `hw.instance` (which I copied into `msft.instance`)?

**Comment by cgyurgyik** [comment]
Precisely

**Comment by teqdruid** [comment]
You might remove the MSFT tags to make it clear that your question is really about `hw.instance`. I don't have an answer.

**Comment by cgyurgyik** [comment]
The tag implies the issue I am concerned with is within both the MSFT and HW dialects. Both `hw.instance` and `msft.instance` follow this behavior.

**Comment by lattner** [comment]
I'm not sure what you mean - are you asking why it is:

```
Operation *InstanceOp::getReferencedModule() {
  auto topLevelModuleOp = getParentOfType<ModuleOp>();
  if (!topLevelModuleOp)
    return nullptr;
```

and not:

```
Operation *InstanceOp::getReferencedModule() {
  auto topLevelModuleOp = getParentOfType<ModuleOp>();
  assert(topLevelModuleOp); 
```

?

If so, the reason is that this was used for printing, and the printing logic has-to / should be cooperative with malformed IR.
