### ISSUE TITLE
[Calyx] Add non-combinational library primitive operations

### ISSUE THREAD

**Issue by mortbopet** [llvm/circt#1811]
The native Calyx library implements a number of primitive operators ([1](https://github.com/cucapra/calyx/blob/master/primitives/core.futil), [2](https://github.com/cucapra/calyx/blob/master/primitives/binary_operators.futil)). Currently, there exists support for all of the combinational operators (https://github.com/llvm/circt/blob/main/include/circt/Dialect/Calyx/CalyxPrimitives.td#L128).

To expand the set of programs which may be lowered to Calyx, support for sequential (multi-cycle) primitives should be added to the Calyx dialect, most importantly integer multiplication and division: 
(https://github.com/cucapra/calyx/blob/master/primitives/binary_operators.futil#L131-L149).

**Comment by cgyurgyik** [comment]
This is complete.
