### ISSUE TITLE
[HW] ParamDeclAttr printer aborts

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#1859]
https://github.com/llvm/circt/blob/4379fab383edf6da8bb86d04ae6a41970e620b9f/lib/Dialect/HW/HWAttributes.cpp#L61

This function gets called from the Python debugger and promptly crashes the debugger. In general, it's a bad idea to have side-effectful print functions since they can get called from anywhere -- especially when debugging. It needs to print _something_ even if that something is that error message. The `abort()` is particularly heinous.

**Comment by lattner** [comment]
Good call, sorry I didn't know it caused a problem, thanks for letting me know will fix.

**Comment by lattner** [comment]
Fixed in 3fd09246, thanks!

**Comment by teqdruid** [comment]
Thanks for the quick turnaround!
