### ISSUE TITLE
[All Dialects] Deprecated OpBuilder format

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#186]
With #184 we get a bunch of warnings:
```
/home/jodemme/circt/include/circt/Dialect/SV/Statements.td:74:1: warning: Op uses a deprecated, string-based OpBuilder format; use OpBuilderDAG with '(ins <...>)' instead
def AlwaysAtPosEdgeOp : SVOp<"alwaysat_posedge", [HasRegionTerminator]>,
```

**Comment by seldridge** [comment]
For more info about this, there's a nice post: https://llvm.discourse.group/t/deprecation-opbuilder-signature-ods-form-use-opbuilderdag-instead/2101/3

While we don't have a ton of ODS stuff to migrate, there is a tool provided to help with the migration.

**Comment by mikeurbach** [comment]
Thanks!
