### ISSUE TITLE
[Calyx][SCFToCalyx] Move control simplifcation from SCFToCalyx to canonicalization methods.

### ISSUE THREAD

**Issue by mortbopet** [llvm/circt#1860]
The SCToCalyx pass introduced a variety of simplification and cleanup patterns, https://github.com/llvm/circt/pull/1849. The cleanup patterns are necessary for allowing the generated Calyx program to pass the Calyx verifiers. However, the simplification patterns can be seen as generally applicable and thus are distinct from the conversion pass itself.

As such, the simplification patterns should be moved to a separate pass which may be run on any Calyx program.

- [X] SeqOp #1883
- [X] ParOp #1883
- [ ] IfOp (@cgyurgyik: working on it).

**Comment by mikeurbach** [comment]
Sounds great to me. I'd suggest an API along the lines of `populateCalyxSimplificationPatterns(RewritePatternSet &patterns)` for other passes to easily plug in. Another option: do these meet the criteria for [canonicalization](https://mlir.llvm.org/docs/Canonicalization/)? We could define a cost model (probably in a rationale doc), and add patterns that always reduce the cost as canonicalizations.

**Comment by mortbopet** [comment]
As far as i can tell, the patterns should fit within the definition of canonicalizations, so that is most likely the way to go!

**Comment by cgyurgyik** [comment]
Going to knock this out.

**Comment by cgyurgyik** [comment]
For `IfOp`, I'll address this in #1861.
