### ISSUE TITLE
[Calyx] [SCFToCalyx]  Add canonicalization for `commonIfEnableTailPattern`.

### ISSUE THREAD

**Issue by mortbopet** [llvm/circt#1861]
https://github.com/llvm/circt/pull/1849 introduced the `CommonIfTailEnablePattern` for simplifying `if` operations with identical groups in the tail position of each branch's `seq` operation.

A similar simplification pattern can be implemented for shared parallel group statements - any shared `group.enable` within each of the par blocks in the branches can be factored out:
```
if %a with %A {
  par {
    calyx.enable @A
    calyx.enable @B
    calyx.enable @C
  }
} else {
  par {
    calyx.enable @B
    calyx.enable @C
    calyx.enable @D
  }
}
```

simplifies to
```
if %a with %A {
  par {
    calyx.enable @A
  }
} else {
  par {
    calyx.enable @D
  }
}
par {
  calyx.enable @B
  calyx.enable @C
}
```

**Comment by cgyurgyik** [comment]
Going to take this on as well. This will require also looking at the `{SeqOp, ParOp}` case.

**Comment by cgyurgyik** [comment]
One thing that makes this a bit trickier is the extra information regarding what the `IfOp` is nested in.
