### ISSUE TITLE
[FIRRTL] Annotation Parsing Performance Bug

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#1971]
As found by @Ramlakshmi3733, large designs seem to exhibit bad scaling performance with the existing FIRRTL Parser's annotation parsing/scattering.  I don't have a minimal example, but a "large" design is spending 50% of its total compile in the parser and ~60% of the parser time appears to be dealing with annotations. (This was tested by running with and without an annotation file.)

We should figure out what's going on here.  This likely involves moving the annotation scattering/application into the annotation handling pass and removing the old processing logic.

**Comment by lattner** [comment]
is this still an issue?

**Comment by seldridge** [comment]
I'm pretty sure this is fixed. Will close. If we have a concrete use case we can reopen.
