### ISSUE TITLE
[web page] circt.llvm.org docs aren't updating

### ISSUE THREAD

**Issue by lattner** [llvm/circt#2007]
The circt.llvm.org web page has a hosted version of the rendered markdown docs in circt/docs, e.g. see [this page](https://circt.llvm.org/docs/RationaleHW-SV/).  These don't see to be updated though.  Do we have a broken action or cron job somewhere?

**Comment by drom** [comment]
Yep. it got stuck for some reason. Restarted.

**Comment by teqdruid** [comment]
This seems to work now.
