### ISSUE TITLE
[FIRRTL] LowerToRTL Unhandled op failure

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#206]
Consider:
module {
  firrtl.circuit "foo" {
    firrtl.module @bar(%io_cpu_flush: !firrtl.uint<1>) {}
    firrtl.module @foo() {
      %fetch = firrtl.instance @bar {name = "fetch"} : !firrtl.bundle<io_cpu_flush: flip<uint<1>>>
      %1454 = firrtl.subfield %fetch("io_cpu_flush") : (!firrtl.bundle<io_cpu_flush: flip<uint<1>>>) -> !firrtl.flip<uint<1>>
      %hits_1_7 = firrtl.node %1454 {name = "hits_1_7"} : !firrtl.flip<uint<1>>
      %1455 = firrtl.asPassive %hits_1_7 : (!firrtl.flip<uint<1>>) -> !firrtl.uint<1>
    }
  }
}

FIRRTLLowering::handleUnloweredOp inserts a StdIntCast to a flipped type which fails to verify.

**Comment by mikeurbach** [comment]
I think I was running into this while testing https://github.com/llvm/circt/pull/157. I wasn't sure what to do about it, so I'm glad to see you've opened this issue. Let me know if i can help out.

**Comment by darthscsi** [comment]
@mikeurbach, you can see if the pr helps you out.
