### ISSUE TITLE
[SV] Add a File Descriptor Parameter to FWriteOp 

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#2062]
Currently, `sv::FWriteOp` will always write to stderr because it has a hard-coded file descriptor.  Change this so that it takes a file descriptor parameter and update `ExportVerilog` to lower this correctly.

This would likely benefit from some enumerated types in the SV dialect for different, common file descriptors, i.e., stdout (`32'h80000001`) and stderr (`32'h80000002`).

**Comment by lattner** [comment]
+1

**Comment by nandor** [comment]
Can I take this one?

**Comment by seldridge** [comment]
@nandor: All yours. 👍
