### ISSUE TITLE
[SCFToCalyx] Incorrect assumptions for memory inlining.

### ISSUE THREAD

**Issue by cgyurgyik** [llvm/circt#2108]
Currently, the SCFToCalyx pass assumes that if there is a single load from a given memory, then it can be "inlined."

This means a body with a read and write to the same memory will be inlined. This leads to two individual problems:

1. We probably shouldn't be reading and writing to the same memory within the same group.
2. Address ports are assigned twice; this is illegal.

**Comment by mortbopet** [comment]
I'd think that a fix to this is to also consider write ops in the following:
https://github.com/llvm/circt/blob/7a31ba0d2e1c5c59925fc627a999b3bd227af284/lib/Conversion/SCFToCalyx/SCFToCalyx.cpp#L105-L109
