### ISSUE TITLE
[HWMemSimImpl] Generating slice syntax for no reason

### ISSUE THREAD

**Issue by lattner** [llvm/circt#2175]
I'm seeing a lot of diffs like this, we should go back to the old form.  I don't see where in the codebase we are creating ArraySliceOp's though!

```
   reg [27:0] Memory[0:31];
 
   always_ff @(posedge RW0_clk) begin
     if (RW0_en & RW0_wmask & RW0_wmode)
-      Memory[RW0_addr] <= RW0_wdata;
+      Memory[RW0_addr][32'h0 +: 28] <= RW0_wdata;
   end // always_ff @(posedge)
```

We should also canonicalize away ArraySliceOp's of their entire contents.

**Comment by lattner** [comment]
Ah, these are IndexedPartSelect's!

**Comment by lattner** [comment]
@prithayan can you take a look at this, this looks like a regression form your recent patch.

**Comment by lattner** [comment]
One way to solve this would be to make `IndexedPartSelectInOutOp` have a folder that nukes noop selects, and change HWMemSimImpl to use createOrFold instead of `create<IndexedPartSelectInOutOp>`

**Comment by prithayan** [comment]
Thanks Chris, this was next on my TODO list. The HWMemSimImpl is creating these ops unnecessarily. Will add the folders.

**Comment by lattner** [comment]
Thanks!
