### ISSUE TITLE
[FIRRTL/IMConstantProp] Explosive time consumption of IMCP

### ISSUE THREAD

**Issue by uenoku** [llvm/circt#2295]
From https://github.com/llvm/circt/commit/c351dc601722fbb3d5884ce786bf67321c63b0dc, we are spending explosive time(50 minutes!) in IMCP  for the chipyard test.
https://github.com/circt/perf/blob/gh-pages/chipyard.TestHarness.RocketSmall1Medium1Big1_BoomMedium1Large1Mega1.top.v.lo-2021-12-05.log
![Screenshot from 2021-12-06 16-47-29](https://user-images.githubusercontent.com/19691120/144858177-b35fe788-eb1e-4dd4-bcee-7b6619a8e561.png)

I suspect this comes from the visiting order of operations in IMCP. Currently, IMCP visits an operation immediately if a lattice value of one of its operands changes. I think this is the problem: Fox example,
```
registers: reg1, reg2, reg3, reg4, ...., reg_m

reg1 <= UInt(1)
reg2 <= UInt(2)
reg3 <= UInt(3)
....
reg_m <= UInt(m)

sum <= add(reg1, reg2, reg3, ..., reg_m)

use1 <= unary_op(sum)
use2 <= unary_op(use1)
use3 <= unary_op(use2)
use4 <= unary_op(use3)
...
use_n <= unrary_op(use_{n-1}) 
```
In this example, we first visit reg1's initialization and then we visit all use-chains of `reg1`. So we visit `sum, use1, use2, use3, ..., use_n` (under the condition that `reg2, reg3 ...., reg_m` are invalid values). After that, we visit `reg2`'s initialization and then we again compute all the values of `sum, use1, use2, ..., use_n`. This repeats until `reg_m` so it will become O(nm) computations eventually. If we change the traversal order from LIFO to FIFO we can initialize all the registers before visiting their use-chains.

This behaviour is not exposed because we gave up invalid canonicalizations in many cases before. I have some fixes in my mind:
1. Change the order of traversal from LIFO to FIFO. It is sufficient to use queue instead of stack as a data structure of `changedLatticeValueWorklist`. I locally confirmed that this works well for the chipyard test.
2. Construct a dependency graph and visit based on SCC. 

WDYT @lattner?

**Comment by uenoku** [comment]
I opened the fix PR for now https://github.com/llvm/circt/pull/2297

**Comment by uenoku** [comment]
![image](https://user-images.githubusercontent.com/19691120/145246270-79cecbfa-4e63-4211-a495-ea627217f827.png)

Ok, it looks fine

**Comment by lattner** [comment]
Thank you for catching this, should this issue be closed now?

**Comment by uenoku** [comment]
Yes, I'm fine with closing it. We might want to use SCC based approach in the end but the current approach seems sufficient for now.
