### ISSUE TITLE
Fix test cases to use pattern matching

### ISSUE THREAD

**Issue by amaleewilson** [llvm/circt#24]
This has been mentioned in a few PRs, but I think it makes sense for this to be its own thing, since all the tests should be changed to use more sophisticated pattern matching. 

https://llvm.org/docs/CommandGuide/FileCheck.html#filecheck-regex-matching-syntax

**Comment by stephenneuendorffer** [comment]
You can try this: https://reviews.llvm.org/D83924, which generates pattern matches.
