### ISSUE TITLE
[FIRRTL] Inconsistent int type width

### ISSUE THREAD

**Issue by uenoku** [llvm/circt#243]
In [`test/firrtl/test.mlir`,](https://github.com/llvm/circt/blob/688bd0d6f39f20367a305317ca5891dddc301c8f/test/firrtl/test.mlir#L32) there is the following firrtl dialect IR:

```
firrtl.circuit "Top" {
  firrtl.module @Top(%out: !firrtl.flip<uint>,
                     %b: !firrtl.uint<32>,
                     %c: !firrtl.analog<13>,
                     %d: !firrtl.uint<16>) {
    %3 = firrtl.add %b, %d : (!firrtl.uint<32>, !firrtl.uint<16>) -> !firrtl.uint<32>
    ....
  }
}
```
The resulting type of `%3` is given as `uint<32>` but when we look at [`getAddSubResult`](https://github.com/llvm/circt/blob/688bd0d6f39f20367a305317ca5891dddc301c8f/lib/Dialect/FIRRTL/Ops.cpp#L838) it should be `uint<33>`.
There are several inconsistent types in tests (basically related to add/sub op). Is it allowed or should we just prohibit this in the verifier?

**Comment by lattner** [comment]
Good catch, I think the verifier should reject this.  We should incorporate getResultType into the verifier, maybe through a new trait that all FIRRTL primitive get?

**Comment by lattner** [comment]
Verifier enhanced in 9899b30, and the testsuite was fixed in previous patches.
