### ISSUE TITLE
LLVM Merge would be helpful

### ISSUE THREAD

**Issue by lattner** [llvm/circt#2456]
[This patch in mainline MLIR](https://reviews.llvm.org/D117187) will be a huge performance benefit in some cases, [resolving this problem](https://llvm.discourse.group/t/speeding-up-operationname-operationname/5100).

It would be great to merge in a new MLIR when it lands.  This will allow me to dig deeper into circt compile time performance.

**Comment by uenoku** [comment]
Done in https://github.com/llvm/circt/commit/7205a2cb2dd5c30d5663574e867f0111ed105a47
