### ISSUE TITLE
[RTL] Implement `fold` hook for RTL operations

### ISSUE THREAD

**Issue by lattner** [llvm/circt#252]
Each of the combinatorial operations should support constant folding and similar trivial canonicalizations.  For example, this doesn't get folded with the canonicalize pass:

```
    %false = rtl.constant(false) : i1
    %0 = rtl.zext %false : (i1) -> i2
```

**Comment by youngar** [comment]
`sext` and `zext` folding support was added in https://github.com/llvm/circt/pull/269. (More folding still to be done)

**Comment by lattner** [comment]
Closing, as this is too general to be useful.  Lots of folding exists and missing things should be tracked in individual bugs.
