### ISSUE TITLE
[Handshake] Integration tests broken recently.

### ISSUE THREAD

**Issue by mikeurbach** [llvm/circt#2561]
@mortbopet we don't test these in CI (requires a commercial simulator), but the Handshake integration tests are currently broken, probably by 5fc6ef49b78883890efa1798693d42546294bea4. The failure I'm seeing is:

```
error: 'handshake.buffer' op result 0 has multiple uses.
```

Both tests fail in this way. Let me know if you can see offhand why this fails, or else I'll take a look at it.

**Comment by mortbopet** [comment]
Looks like an issue with forks/sinks not being materialized after buffer insertion. I'll push a quick fix (just add materialization) but will look into why this popped up in the first place.

**Comment by mikeurbach** [comment]
Thanks, that fixes the tests for me. Was hoping it was something like this.
