### ISSUE TITLE
CIRCT should default to building with -fno-exceptions -fno-rtti

### ISSUE THREAD

**Issue by lattner** [llvm/circt#257]
We follow the LLVM standard here, so we should default to not having exceptions or RTTI enabled.  I'm not sure if this is a cmake change or a CI configuration change, but it would be nice to catch this mechanically instead of through code review.

**Comment by stephenneuendorffer** [comment]
I really need to go back and make sure we get all the LLVM defaults here.  I have a patch for this, I just need to resurrect this.

**Comment by xgupta** [comment]
Raised Issue is resolved in #359. Should we close this issue?

**Comment by lattner** [comment]
woo hoo, thank you!
