### ISSUE TITLE
[FIRRTL] Create global constants for annotation class name strings

### ISSUE THREAD

**Issue by prithayan** [llvm/circt#2606]
Promote annotation strings used in various passes to some global constant, for example, 
`lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp :: `
``
StringRef verifBBClass =
        "freechips.rocketchip.annotations.InternalVerifBlackBoxAnnotation";
``

**Comment by dtzSiFive** [comment]
These generally seem to all be in `AnnotationDetails.h` these days, closing!

**Comment by dtzSiFive** [comment]
Found a stray instance, fixed! :smile:
