### ISSUE TITLE
[FIRRTL] change firrtl.instance to return multiple results instead of a bundle

### ISSUE THREAD

**Issue by lattner** [llvm/circt#262]
The current design of `firrtl.instance` is a direct mapping to the .fir file specification, where instance return a single bundles value.  This is a pain to work with, and MLIR supports multiple results.  We should move to a more MLIR native representation to avoid the awkwardness of the bundle.

**Comment by seldridge** [comment]
Fixed via ded5bd2e396a84cc9e277573ce8e83d06b699bd4.

**Comment by lattner** [comment]
thx
