### ISSUE TITLE
[LLVM compiler-rt] Build issue: can not compile it

### ISSUE THREAD

**Issue by rubyFeedback** [llvm/circt#266]
Hey folks,

First, the URL for the tarball I used was this one here:

    https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/compiler-rt-11.0.0.tar.xz

Apologies if I filed this here under the wrong top-level, I am not very familiar with the LLVM internal organization.

Before I copy/paste the error, let me state that I was able to compile llvm from source into
/usr/ successfully. It works too. This is on a linux system, linuxmint but I compile most from
source via ruby scripts.

The URL for LLVM I used was:

https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-11.0.0.src.tar.xz

Next I was using clang, also the /usr/ hierarchy. This one compiled too.

URL was:

https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang-11.0.0.src.tar.xz

Then compiler-rt, which fails. First the URL I was using:

https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/compiler-rt-11.0.0.src.tar.xz

The error is the following (copy/paste follows):

    make

    [  3%] Built target RTfuzzer.x86_64
    Scanning dependencies of target clang_rt.fuzzer_no_main-x86_64
    [  3%] Linking CXX static library ../linux/libclang_rt.fuzzer_no_main-x86_64.a
    [  3%] Built target clang_rt.fuzzer_no_main-x86_64
    [  3%] Built target RTfuzzer_main.x86_64
    Scanning dependencies of target clang_rt.fuzzer-x86_64
    [  3%] Linking CXX static library ../linux/libclang_rt.fuzzer-x86_64.a
    [  3%] Built target clang_rt.fuzzer-x86_64
    Scanning dependencies of target fuzzer
    [  3%] Built target fuzzer
    [  6%] Built target compiler-rt-headers
    [ 27%] Built target clang_rt.builtins-x86_64
    Scanning dependencies of target builtins
    [ 27%] Built target builtins
    [ 27%] Built target clang_rt.crtend-x86_64
    [ 27%] Built target clang_rt.crtbegin-x86_64
    Scanning dependencies of target crt
    [ 27%] Built target crt
    [ 27%] Built target RTLSanCommon.x86_64
    [ 33%] Built target RTSanitizerCommon.x86_64
    [ 34%] Built target RTSanitizerCommonLibc.x86_64
    [ 34%] Built target RTSanitizerCommonCoverage.x86_64
    [ 36%] Built target RTSanitizerCommonSymbolizer.x86_64
    [ 37%] Built target RTInterception.x86_64
    Scanning dependencies of target clang_rt.lsan-x86_64
    [ 37%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan.cpp.o
    [ 38%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_allocator.cpp.o
    [ 38%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_fuchsia.cpp.o
    [ 38%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_interceptors.cpp.o
    [ 38%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_linux.cpp.o
    [ 38%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_mac.cpp.o
    [ 38%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_malloc_mac.cpp.o
    [ 38%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_posix.cpp.o
    [ 39%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_preinit.cpp.o
    [ 39%] Building CXX object lib/lsan/CMakeFiles/clang_rt.lsan-x86_64.dir/lsan_thread.cpp.o
    [ 39%] Linking CXX static library ../linux/libclang_rt.lsan-x86_64.a
    [ 39%] Built target clang_rt.lsan-x86_64
    Scanning dependencies of target lsan
    [ 39%] Built target lsan
    [ 39%] Built target RTUbsan_cxx.x86_64
    Scanning dependencies of target clang_rt.ubsan_standalone_cxx-x86_64
    [ 39%] Linking CXX static library ../linux/libclang_rt.ubsan_standalone_cxx-x86_64.a
    [ 39%] Built target clang_rt.ubsan_standalone_cxx-x86_64
    [ 39%] Built target RTUbsan_standalone.x86_64
    [ 40%] Built target RTUbsan.x86_64
    Scanning dependencies of target clang_rt.ubsan_standalone-x86_64
    [ 40%] Building CXX object lib/ubsan/CMakeFiles/clang_rt.ubsan_standalone-x86_64.dir/ubsan_init_standalone_preinit.cpp.o
    [ 41%] Linking CXX static library ../linux/libclang_rt.ubsan_standalone-x86_64.a

(and so forth ...)

[ 41%] Built target clang_rt.ubsan_standalone-x86_64
Scanning dependencies of target clang_rt.ubsan_standalone-x86_64-symbols
[ 41%] Generating exported symbols for clang_rt.ubsan_standalone-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='ubsan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 41%] Built target clang_rt.ubsan_standalone-x86_64-symbols
[ 41%] Generating version list for clang_rt.ubsan_standalone-dynamic-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='ubsan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Scanning dependencies of target RTUbsan_dynamic_version_script_dummy.x86_64
[ 41%] Building CXX object lib/ubsan/CMakeFiles/RTUbsan_dynamic_version_script_dummy.x86_64.dir/dummy.cpp.o
[ 41%] Built target RTUbsan_dynamic_version_script_dummy.x86_64
Scanning dependencies of target clang_rt.ubsan_standalone-dynamic-x86_64
[ 41%] Linking CXX shared library ../linux/libclang_rt.ubsan_standalone-x86_64.so
[ 41%] Built target clang_rt.ubsan_standalone-dynamic-x86_64
Scanning dependencies of target clang_rt.ubsan_standalone_cxx-x86_64-symbols
[ 41%] Generating exported symbols for clang_rt.ubsan_standalone_cxx-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='ubsan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 41%] Built target clang_rt.ubsan_standalone_cxx-x86_64-symbols
Scanning dependencies of target ubsan
[ 41%] Built target ubsan
[ 42%] Built target RTAsan_preinit.x86_64
[ 46%] Built target RTAsan.x86_64
Scanning dependencies of target clang_rt.asan-x86_64
[ 46%] Linking CXX static library ../linux/libclang_rt.asan-x86_64.a
[ 46%] Built target clang_rt.asan-x86_64
Scanning dependencies of target clang_rt.asan-x86_64-symbols
[ 46%] Generating exported symbols for clang_rt.asan-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='asan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 46%] Built target clang_rt.asan-x86_64-symbols
[ 47%] Built target asan_blacklist
[ 47%] Built target RTAsan_cxx.x86_64
Scanning dependencies of target clang_rt.asan_cxx-x86_64
[ 48%] Linking CXX static library ../linux/libclang_rt.asan_cxx-x86_64.a
[ 48%] Built target clang_rt.asan_cxx-x86_64
[ 48%] Built target clang_rt.asan-preinit-x86_64
[ 52%] Built target RTAsan_dynamic.x86_64
[ 52%] Generating version list for clang_rt.asan-dynamic-x86_64

/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='asan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Scanning dependencies of target RTAsan_dynamic_version_script_dummy.x86_64
[ 52%] Building CXX object lib/asan/CMakeFiles/RTAsan_dynamic_version_script_dummy.x86_64.dir/dummy.cpp.o
[ 52%] Built target RTAsan_dynamic_version_script_dummy.x86_64
Scanning dependencies of target clang_rt.asan-dynamic-x86_64
[ 52%] Linking CXX shared library ../linux/libclang_rt.asan-x86_64.so
[ 52%] Built target clang_rt.asan-dynamic-x86_64
Scanning dependencies of target clang_rt.asan_cxx-x86_64-symbols
[ 52%] Generating exported symbols for clang_rt.asan_cxx-x86_64
[ 52%] Built target clang_rt.asan_cxx-x86_64-symbols
Scanning dependencies of target asan
[ 52%] Built target asan
[ 52%] Built target dfsan_abilist
[ 53%] Built target clang_rt.dfsan-x86_64
Scanning dependencies of target clang_rt.dfsan-x86_64-symbols
[ 53%] Generating exported symbols for clang_rt.dfsan-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='dfsan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 53%] Built target clang_rt.dfsan-x86_64-symbols
Scanning dependencies of target dfsan
[ 53%] Built target dfsan
[ 54%] Built target msan_blacklist
[ 54%] Built target clang_rt.msan_cxx-x86_64
[ 55%] Built target clang_rt.msan-x86_64
Scanning dependencies of target clang_rt.msan-x86_64-symbols
[ 55%] Generating exported symbols for clang_rt.msan-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='msan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 55%] Built target clang_rt.msan-x86_64-symbols
[ 56%] Built target clang_rt.msan_cxx-x86_64-symbols
Scanning dependencies of target msan
[ 56%] Built target msan
[ 56%] Built target hwasan_symbolize
[ 56%] Built target hwasan_blacklist
[ 56%] Built target RTHwasan_cxx.x86_64
Scanning dependencies of target clang_rt.hwasan_cxx-x86_64
[ 56%] Linking CXX static library ../linux/libclang_rt.hwasan_cxx-x86_64.a
[ 56%] Built target clang_rt.hwasan_cxx-x86_64
Scanning dependencies of target clang_rt.hwasan_cxx-x86_64-symbols
[ 56%] Generating exported symbols for clang_rt.hwasan_cxx-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='hwasan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 56%] Built target clang_rt.hwasan_cxx-x86_64-symbols
[ 58%] Built target RTHwasan.x86_64
Scanning dependencies of target clang_rt.hwasan-x86_64
[ 58%] Linking CXX static library ../linux/libclang_rt.hwasan-x86_64.a
[ 58%] Built target clang_rt.hwasan-x86_64
[ 58%] Generating version list for clang_rt.hwasan-dynamic-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='hwasan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Scanning dependencies of target RTHwasan_dynamic_version_script_dummy.x86_64
[ 58%] Building CXX object lib/hwasan/CMakeFiles/RTHwasan_dynamic_version_script_dummy.x86_64.dir/dummy.cpp.o
[ 58%] Built target RTHwasan_dynamic_version_script_dummy.x86_64
[ 60%] Built target RTHwasan_dynamic.x86_64
Scanning dependencies of target clang_rt.hwasan-dynamic-x86_64
[ 60%] Linking CXX shared library ../linux/libclang_rt.hwasan-x86_64.so
[ 60%] Built target clang_rt.hwasan-dynamic-x86_64
Scanning dependencies of target clang_rt.hwasan-x86_64-symbols
[ 60%] Generating exported symbols for clang_rt.hwasan-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='hwasan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 60%] Built target clang_rt.hwasan-x86_64-symbols
Scanning dependencies of target hwasan
[ 60%] Built target hwasan
[ 60%] Built target clang_rt.tsan_cxx-x86_64
Scanning dependencies of target clang_rt.tsan_cxx-x86_64-symbols
[ 61%] Generating exported symbols for clang_rt.tsan_cxx-x86_64
/home/Temp/rbt/compiler-rt-11.0.0/lib/sanitizer_common/scripts/gen_dynamic_list.py:122: ResourceWarning: unclosed file <_io.TextIOWrapper name='rtl/tsan.syms.extra' mode='r' encoding='UTF-8'>
  with open(args.output, 'w') as f:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[ 61%] Built target clang_rt.tsan_cxx-x86_64-symbols
[ 61%] Building C object lib/tsan/CMakeFiles/clang_rt.tsan-x86_64.dir/rtl/tsan_rtl_amd64.S.o
cc1: warning: command-line option ‘-Wno-non-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-fno-rtti’ is valid for C++/D/ObjC++ but not for C
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:7:1: error: expected identifier or ‘(’ before ‘.’ token
    7 | .section .text
      | ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:16:5: error: invalid preprocessing directive #Save
   16 |   # Save scratch registers.
      |     ^~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:44:5: error: invalid preprocessing directive #Align
   44 |   # Align stack frame.
      |     ^~~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:45:14: error: stray ‘#’ in program
   45 |   push %rbx  # non-scratch
      |              ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:48:19: error: stray ‘#’ in program
   48 |   mov %rsp, %rbx  # save current rsp
      |                   ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:50:17: error: stray ‘#’ in program
   50 |   shr $4, %rsp  # clear 4 lsb, align to 16
      |                 ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:55:5: error: invalid preprocessing directive #Unalign
   55 |   # Unalign stack frame back.
      |     ^~~~~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:56:19: error: stray ‘#’ in program
   56 |   mov %rbx, %rsp  # restore the original rsp
      |                   ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:60:5: error: invalid preprocessing directive #Restore
   60 |   # Restore scratch registers.
      |     ^~~~~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:96:5: error: invalid preprocessing directive #Save
   96 |   # Save scratch registers.
      |     ^~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:124:5: error: invalid preprocessing directive #Align
  124 |   # Align stack frame.
      |     ^~~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:125:14: error: stray ‘#’ in program
  125 |   push %rbx  # non-scratch
      |              ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:128:19: error: stray ‘#’ in program
  128 |   mov %rsp, %rbx  # save current rsp
      |                   ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:130:17: error: stray ‘#’ in program
  130 |   shr $4, %rsp  # clear 4 lsb, align to 16
      |                 ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:135:5: error: invalid preprocessing directive #Unalign
  135 |   # Unalign stack frame back.
      |     ^~~~~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:136:19: error: stray ‘#’ in program
  136 |   mov %rbx, %rsp  # restore the original rsp
      |                   ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:140:5: error: invalid preprocessing directive #Restore
  140 |   # Restore scratch registers.
      |     ^~~~~~~
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:212:41: error: stray ‘@’ in program
  212 |   movq _ZN14__interception11real_setjmpE@GOTPCREL(%rip), %rdx
      |                                         ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:250:42: error: stray ‘@’ in program
  250 |   movq _ZN14__interception12real__setjmpE@GOTPCREL(%rip), %rdx
      |                                          ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:308:44: error: stray ‘@’ in program
  308 |   movq _ZN14__interception14real_sigsetjmpE@GOTPCREL(%rip), %rdx
      |                                            ^
/home/Temp/rbt/compiler-rt-11.0.0/lib/tsan/rtl/tsan_rtl_amd64.S:358:46: error: stray ‘@’ in program
  358 |   movq _ZN14__interception16real___sigsetjmpE@GOTPCREL(%rip), %rdx
      |                                              ^
make[2]: *** [lib/tsan/CMakeFiles/clang_rt.tsan-x86_64.dir/build.make:472: lib/tsan/CMakeFiles/clang_rt.tsan-x86_64.dir/rtl/tsan_rtl_amd64.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4951: lib/tsan/CMakeFiles/clang_rt.tsan-x86_64.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

----------
Not entirely sure what the error is about.  gcc I use is 10.2.0 via: /home/Temp/rbt/gcc-10.2.0/configure --prefix=/home/Programs/Gcc/10.2.0/ --enable-languages=c,c++,objc,go,fortran --disable-bootstrap --disable-libstdcxx-pch --disable-multilib

Anyway please feel free to just disregard this if it is not applicable. As said llvm and clang works fine, only compiler-rt seems to struggle with something.

**Comment by stephenneuendorffer** [comment]
Hi!  This github project is specific for the 'circt' project.  You're best bet is probably to ask on the llvm-dev mailing list, or you can try asking on one of the discord forums.  see: https://llvm.org/
