### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by youngar** [llvm/circt#2685]
The windows build is broken: https://github.com/llvm/circt/runs/5324502918?check_suite_focus=true#step:7:1925
```
ninja: error: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/DIA SDK/lib/amd64/diaguids.lib', needed by 'bin/circt-lsp-server.exe', missing and no known rule to make it
```

The first commit to show this issue is https://github.com/llvm/circt/commit/e2e849af9fb83a59e7922e08d36d720178d7b8f0 although I don't know how this change could cause that.

I am guessing it is a result of a change in build environment or the previous LLVM bump (https://github.com/llvm/circt/commit/a0e883136331c4a05ac366d5b31962a9de8d803b)

**Comment by teqdruid** [comment]
Since the bump compiled successfully, I suspect a build environment change.
I'm re-running the last bump build to check: https://github.com/llvm/circt/actions/runs/1891200560

**Comment by teqdruid** [comment]
Yep. Build environment change.

**Comment by teqdruid** [comment]
I _suspect_ we got bumped to server 2022. Test build with downgrade: https://github.com/llvm/circt/actions/runs/1895364998

**Comment by teqdruid** [comment]
Made it through config, so yeah. Might not have been bumped, but downgrading fixed it.

**Comment by youngar** [comment]
I'm just noticing it says we were bumped in the Summary page:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/2892549/155612570-7c92d6aa-f31c-4fe7-bc67-8c913d4e7a4d.png">

**Comment by youngar** [comment]
also, thanks for fixing this! 😁

**Comment by teqdruid** [comment]
Serves me right for not reading the warnings!
