### ISSUE TITLE
[CI] Nightly integration tests

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#2843]
Some of the nightly integration tests have started failing due to not enough disk space on the agents. Mostly gcc debug tests.

Are there some cmake flags we can set to prevent building unrelated files in LLVM/MLIR? (It always bugs me to see OpenMPI and GPU stuff when I compile.) Should we selectively disable the gcc debug tests?

**Comment by uenoku** [comment]
I think one thing we can try is to stop building backends other than X86.  I'm not sure how much it helps but I bet it should reduce unrelated lib sizes.

**Comment by teqdruid** [comment]
@uenoku good idea!

@mikeurbach The ccache may be the primary source of bloat. The short nightly test uses the ccache action... did not using it on the nightlies make any difference in hit rates?

**Comment by teqdruid** [comment]
@mikeurbach Nevermind. The ccaches on failing builds are actually quite small:

![image](https://user-images.githubusercontent.com/1498080/161650136-a981e563-aadb-41a3-af28-84f7478a4659.png)

**Comment by uenoku** [comment]
Passed CI (https://github.com/llvm/circt/actions/runs/2092757865) with #2845. 
Though I do believe it reaches the limit again in the near future.

**Comment by teqdruid** [comment]
> Though I do believe it will reach the limit again in the near future.

That sounds like a problem for future us ;)

Thanks!
