### ISSUE TITLE
[FIRRTL][InferResets] Incorrect field ID with zero length vectors

### ISSUE THREAD

**Issue by youngar** [llvm/circt#2857]
InferResets uses `fieldRef`s to track specific reset element types in aggregates. There is a mismatch in that `fieldRef`s were not designed to track specific elements types in an aggregate type, but values of an aggregate value.  This is evident when looking at how InferRests uses fieldRefs for vectors: it references the first element of the array to represent the element type.  This is problematic when there is a bundle with a 0 length vector, and the `fieldRef` which is meant to target the element type of the vector ends up targeting the bundle element type after the vector:

```scala
circuit Foo:
  module Foo :
    output out : { resets : Reset[0], flip data : UInt<3> }
    out.resets is invalid
```

```
reset.fir:4:16: error: 'firrtl.strictconnect' op requires all operands to have the same type
    out.resets is invalid
               ^
reset.fir:4:16: note: see current operation: "firrtl.strictconnect"(%0, %1) : (!firrtl.vector<reset, 0>, !firrtl.vector<uint<1>, 0>) -> ()
// -----// IR Dump After InferResets Failed //----- //
"firrtl.circuit"() ({
  "firrtl.module"() ({
  ^bb0(%arg0: !firrtl.bundle<resets: vector<reset, 0>, data flip: uint<1>>):
    %0 = "firrtl.subfield"(%arg0) {fieldIndex = 0 : i32} : (!firrtl.bundle<resets: vector<reset, 0>, data flip: uint<1>>) -> !firrtl.vector<reset, 0>
    %1 = "firrtl.invalidvalue"() : () -> !firrtl.vector<uint<1>, 0>
    "firrtl.strictconnect"(%0, %1) : (!firrtl.vector<reset, 0>, !firrtl.vector<uint<1>, 0>) -> ()
  }) {annotations = [], portAnnotations = [], portDirections = true, portNames = ["out"], portSyms = [], portTypes = [!firrtl.bundle<resets: vector<reset, 0>, data flip: uint<1>>], sym_name = "Foo"} : () -> ()
}) {annotations = [], name = "Foo"} : () -> ()
```

In addition to failing to update the type of `resets`, causing a `firrtl.strictconnect` verifier error, it changes the type of the `data` field from `uint<3>` to `uint<1>`.

Hopefully this shows the numbering difference for the following bundle type: `out: { resets : Reset[0], flip data : UInt<3> }`
Field based numbering:
- 0: `out`
- 1: `out.resets`
- 2: `out.data`

Type based numbering:
- 0: `{ resets : Reset[0], flip data : UInt<3> }`
- 1: `Reset[0]`
- 2: `Reset`
- 3: `UInt<3>`

I think the way to solve this is to stop using the generic `fieldRef` utility and reimplement numbering scheme specifically to work with types.

**Comment by fabianschuiki** [comment]
I think `InferResets` wants to use field refs for tracking aggregate values, but then confuses a few things and messes up the IDs. Trying to track individual vector element types seems like a bug, since all `InferResets` can do at the end of the day is pick a reset type for _all_ elements at once. The solution here might be to stop resolving individual vector elements 🤔 when finding the sets of connected reset values and wires.

**Comment by fabianschuiki** [comment]
Fantastic catch btw @youngar :grin: :tada: !
