### ISSUE TITLE
[RTL] Add NotOp

### ISSUE THREAD

**Issue by youngar** [llvm/circt#300]
RTL does not currently have a not op.

**Comment by lattner** [comment]
`~x` can be represented in canonical form as `x ^ -1`, elimination of not as a thing allows all the patterns that apply to xor to work on it.

**Comment by youngar** [comment]
Closing this since we will not be adding an `rtl.not(%arg0)` operation. In case anyone in the future wants something to copy and paste, here is what you should do instead:

```mlir
%c-1_i8 = rtl.constant(-1 : i8) : i8
%1 = rtl.xor(%0, %c-1_i8) : i8
```
