### ISSUE TITLE
[FIRRTL] Mega Nit: Double Spaces in FIRRTL Serialized Format

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#3367]
This is the biggest of nits, but there are a lot of double spaces (`  `) in printed FIRRTL Dialect that always annoy me to see. It would be nice if we could clean these up in the custom

E.g.:
```scala
circuit Foo:
  module Bar:
    skip
  module Foo:

    inst bar of Bar
```

```mlir
module {
  firrtl.circuit "Foo"  {
    firrtl.module private @Bar() {
      firrtl.skip
    }
    firrtl.module @Foo() {
      firrtl.instance bar interesting_name  @Bar()
    }
  }
}
```

There's a double space after `interesting_name`. 👹

**Comment by uenoku** [comment]
Double space after namekind is partially fixed by https://github.com/llvm/circt/pull/3370
Another issue is that we cannot know whether or not `printOptionalAttrDict` actually emits string. 
Therefore we currently are emitting double-space if attributes are empty.
