### ISSUE TITLE
`llhd-sim` doesn't link on Windows

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#375]
`llhd-sim` fails to link on Windows since it can't find `circt-llhd-signals-runtime-wrappers.lib`. CMake on Windows (at least our `CMakeLists.txt`s) doesn't know how to link a `SHARED` lib (`circt-llhd-signals-runtime-wrappers`) to a statically compiled executable.

**Comment by mikeurbach** [comment]
Closed by #789
