### ISSUE TITLE
test/handshake-runner/matmul-check-std.mlir takes too long for regression tests.

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#3812]
almost 50% of the runtime of a regression test is taken running test/handshake-runner/matmul-check-std.mlir .  This is long enough it needs to be moved to integration tests or sped up consierably.

**Comment by mikeurbach** [comment]
We could probably move all those handshake-runner tests to integration tests, since that seems more appropriate. These are actually compiling to LLVM IR and running it with the LLVM JIT to compare the results.

**Comment by Dinistro** [comment]
Moving such things to the integration test is the way to go, I think. Currently, many tests around handshake are too large, which makes them slow and hard to debug. See https://github.com/llvm/circt/issues/3668
