### ISSUE TITLE
[StandardToHandshake] Loop task pipelining drops threads

### ISSUE THREAD

**Issue by Dinistro** [llvm/circt#3818]
While writing additional tests for the `std-to-handshake` pass, I uncovered an issue related to loop task pipelining. 
The test defined [here](https://github.com/llvm/circt/tree/dinistro/more-task-pipeline-tests/integration_test/Dialect/Handshake/multiple_loops) breaks down as it does not emit all results. 
Independent of the input sequence, the 6th thread is always dropped. Note that his only happens for the buffer strategies `all` and `allFIFO`.

Either this is caused by a faulty test driver or there is indeed a deeper issue in the loop protection strategy. 

CC @mortbopet

**Comment by mortbopet** [comment]
I think a trace and/or running with HSDBG from CIRCT-HLS would clarify what is going wrong here.

**Comment by Dinistro** [comment]
Is it possible to import foreign traces into `hsdbg`?

I exported a trace from cocotb as described in https://docs.cocotb.org/en/stable/simulator_support.html and am now inspecting it in an external tool. It seems that the driver is faulty and accidentally does send the next element, even though the previous handshake didn't occur. 
![image](https://user-images.githubusercontent.com/15726717/188382598-193f35e7-958a-40e5-95f6-1a50fc502561.png)

I'll try to fix this in the `cocotb` helper's file.
