### ISSUE TITLE
[Handshake] Remove the requirement for a ctrl signal in a function.

### ISSUE THREAD

**Issue by Dinistro** [llvm/circt#3862]
While all circuits produced by `std-to-handshake` do have a control signal, this is in theory not required for a `handshake.func`. My downstream work can produce circuits that do not have any outputs, but circuits without inputs are possible as well.

**Comment by mortbopet** [comment]
100% agree - the `ctrl` signal is an assumption based purely on DHLS but the Handshake (dataflow) abstraction is obviously not _just_ a DHLS lowering.

**Comment by mortbopet** [comment]
closed in a610303a74af6d5fa48dc6c4810ab6b9b3ea0f2b
