### ISSUE TITLE
Windows CI: doesn't find "lit", doesn't run tests

### ISSUE THREAD

**Issue by dtzSiFive** [llvm/circt#4028]
From https://github.com/llvm/circt/actions/runs/3154831600/jobs/5132861406#step:7:64 (for example):

```
 CMake Warning at llvm/install/lib/cmake/llvm/AddLLVM.cmake:1821 (message):
  LLVM_EXTERNAL_LIT set to
  D:\a\circt\circt\build_release/../llvm/build/Release/bin/llvm-lit.py, but
  the path does not exist.
Call Stack (most recent call first):
  llvm/install/lib/cmake/llvm/AddLLVM.cmake:1866 (get_llvm_lit_path)
  llvm/install/lib/cmake/llvm/AddLLVM.cmake:1956 (add_lit_target)
  test/CMakeLists.txt:42 (add_lit_testsuite)
```

This goes back at least through August 1st, let's see if can't fix this...

Might have broke when moving to ninja (?) which doesn't put bits into folders based on build config ("Release") like other build systems do, at least on other platforms... (investigating)

**Comment by teqdruid** [comment]
the tests themselves don't pass on Windows (https://github.com/llvm/circt/issues/376), so...
