### ISSUE TITLE
[ExportVerilog] Instance name collisions

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#407]
https://github.com/llvm/circt/blob/27155e4d1740dc44bd596a0a04ca961b2136d014/lib/Translation/ExportVerilog/ExportVerilog.cpp#L1494

ExportVerilog just spits out instance names. If you've got two instances with the same name (as I'd imagine is frequent in generated code), they will conflict in the output. Those names may also conflict with other identifiers, such as wires and ports.

We should at least error out in the case where an instanceName conflicts with another idenifier. I think we should go further and automatically rename the instance.

**Comment by lattner** [comment]
I agree with autorename.  I think that each module should have an instance name table similar to `nameTable` but for instances.

**Comment by mikeurbach** [comment]
Is anyone working on this? I can take a crack at it.

**Comment by teqdruid** [comment]
I'm not and it's a good bet nobody else is either given that its been here for awhile.
