### ISSUE TITLE
[FIRRTL] Add Support for Module Port Source Locators

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#4185]
Chisel is going to start emitting source locators for module ports in 3.6. We should get CIRCT ready for this. This requires adding a `portSourceLocators` array attribute (or something like this) to FIRRTL modules so that there is a receptacle for this information.

This likely motivates a similar thing for HW modules and similar, but it is not necessary to land this all at once.

h/t @jackkoenig

**Comment by dtzSiFive** [comment]
Looking into this a bit, maybe this was already known but for those interested:

1) We already parse them from the FIRRTL (!), so at least it's safe to point firtool at files with them included.
2) BlockArgument's already support locations, which is where they're stored where applicable (d7bebee47118edd5b0f924a730827f44953aa549) for Modules with bodies (`FModuleOp`).  Modules without BlockArguments like  FExtModuleOp and similar don't get port location information presently (mentioned in the linked commit).
3) These locations are not preserved when printing/parsing the IR.  This should be straightforward to address.
4) PortInfo includes the location information when present (on BlockArgument's) -- it has a field for location information, so at least API using these is compatible with adding this information, however it's stored.

Attaching them to the BlockArguments seems nice (diagnostics? already part of the BlockArgument's storage?), so I'm thinking we only have the `portSourceLocators` attribute when needed (the other ops).  WDYT?

This information seems a lot less important / likely to be useful for external modules (and `FMemModule`'s?) so maybe that's not a priority, but doesn't seem like a big deal to support while adding support for this.

Once supported, would be good to audit our passes/code (and lowering of course) to ensure they're propagated/merged-- dedup, inlining, inserting ports, etc.  This can come later beyond ensuring they make it the output at least "usually".

I think this would be straightforward to add to to ExportVerilog, which is already looping over `PortInfo`'s (for "modules").

Haven't looked into how any of this does/doesn't work for HW's IR constructs yet :smile:.
