### ISSUE TITLE
[FIRRTL] Extend lower types with partial connect support

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#419]
Add support to FIRRTL type lowering to work with partial connects `<-`. 

This is both used by "Chisel 2 compatibility mode" and it's been discussed that Chisel should emit these instead of normal connects (`<=`) for the reason that Chisel and the Scala FIRRTL Compiler (SFC) incorrectly truncate `<=` (which is supposed to only be a feature of `<-`).

Currently, `firtool` will throw a stack trace if you have any partial connects.

Example input that currently fails:

```scala
circuit Foo:
  module Foo:
    input a: { a: UInt<1>, b: UInt<1> }
    output b: { a: UInt<1> }

    b <- a
```

With the SFC, you get the following lowered circuit:

```scala
circuit Foo :
  module Foo :
    input a_a : UInt<1>
    input a_b : UInt<1>
    output b_a : UInt<1>

    b_a <= a_a
```

Currently CIRCT will crash with this.

**Comment by lattner** [comment]
Still crashes
