### ISSUE TITLE
[FIRRTL] Remove node name attribute if the same as Value

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#421]
Don't print out the `name` attribute if it's the same as the SSA value name for a node. This already happens for `wire`, but not for `node.

Currently, things print as:

```mlir
%x = firrtl.node %a {name = "x"} : !firrtl.uint<1>
```

When this could be simplified to:

```mlir
%x = firrtl.node %a : !firrtl.uint<1>
```

Similar to #90.

**Comment by lattner** [comment]
+1.  I wonder if the `custom<>` thing that @teqdruid added could be used for this?  Is it possible to do:

`$input custom<Fancy>(attr-dict) `:` type($input)`

?
