### ISSUE TITLE
[PyCDE] Write a pycde install cmake target

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#4344]
We currently use the "check-pycde" target when building the wheel. The new target should assemble all the necessary files and place them in the install directory to be packaged into the wheel.

**Comment by mikeurbach** [comment]
I believe there should be a target named `install-PyCDE` already, can that be used?

**Comment by teqdruid** [comment]
IIRC it's broken. Especially with the new BSP support which require aux
files.

**Comment by mikeurbach** [comment]
I see. Well maybe it can be customized, since that seems like the "right" target to use for this.

**Comment by teqdruid** [comment]
I agree that's the correct target.

**Comment by teqdruid** [comment]
I think I took care of this awhile back such that building the PyCDE target works and `cmake --install --component PyCDE` works.
