### ISSUE TITLE
[StandardToHandshake] Taking fork/sink materialization out of conversion pass

### ISSUE THREAD

**Issue by RamirezLucas** [llvm/circt#4362]
Currently, the `StandardToHandshake` conversion pass performs fork/sink materialization during the conversion process. [As a comment in the code says](https://github.com/llvm/circt/blob/main/include/circt/Conversion/StandardToHandshake.h#L178), it would be better for this do be done at user's request after initial dataflow conversion.

I'm trying to take a shot at this. More broadly, I'm trying to address the open issues on `StandardToHandshake` and figured doing that first might simplify other fixes down the line. The main issue with removing fork/sink materialization is that [connectToMemory](https://github.com/llvm/circt/blob/main/lib/Conversion/StandardToHandshake/StandardToHandshake.cpp#L1626) depends on it, which is what I'm trying to address currently. 

Are there other parts of the implementation that would be affected by the removal of fork/sink materialization during dialect conversion? I don't see any right now but if there is one and you can point me to it it would be super helpful!

**Comment by mortbopet** [comment]
> Are there other parts of the implementation that would be affected by the removal of fork/sink materialization during dialect conversion? I don't see any right now but if there is one and you can point me to it it would be super helpful!

Haven't touched the "older" parts of standard-to-handshake in a while so i don't have any immediate pointers here.

I'm suspecting that it might be worth tackling https://github.com/llvm/circt/issues/3687 before this issue, since the cases listed in that PR places some **nasty** assumptions on the inflight IR state.

**Comment by RamirezLucas** [comment]
> I'm suspecting that it might be worth tackling https://github.com/llvm/circt/issues/3687 before this issue, since the cases listed in that PR places some nasty assumptions on the inflight IR state.

Thanks for your input and for editing the snippets on #3687. I'll tackle it first then.
