### ISSUE TITLE
[FIRRTL] Parsing broken for "an instance called module"

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#4564]
FIRRTL parsing is broken for the following circuit:

```
circuit Foo:
  module Bar:
    skip

  module Foo:

    inst module of Bar
```

The parser thinks that `module` has to be the first token when it can be an identifier:

```
build/Bar.fir:7:10: error: 'module' must be first token on its line
    inst module of Bar
         ^
```

h/t @chick for finding this one.

**Comment by youngar** [comment]
dupe of https://github.com/llvm/circt/issues/3363
