### ISSUE TITLE
[Web site] Diagrams not appearing on getting started page

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#4578]
![image](https://user-images.githubusercontent.com/1498080/214150925-e2a4e916-278c-46c8-9b21-396d5acbf617.png)

 https://circt.llvm.org/docs/GettingStarted/

The diagram links are broken on the published site whereas they work in github. They are relative paths, but compiling to the site makes GettingStarted.md a directory but doesn't fix the links appropriately. Ideally, they'd work in both places but I'm unsure how to accomplish this.

@drom any thoughts?

**Comment by dtzSiFive** [comment]
This sounds like same issue as in #4343 (and issue linked from there)?

**Comment by teqdruid** [comment]
Yep. same issue. Will close and comment there.
