### ISSUE TITLE
[ExportVerilog] Zero width module ports which appear last in a port list cause syntax errors

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#471]
As [noted in the code](https://github.com/llvm/circt/blob/1606160e433d378d188f214090c4f2c473e78e70/lib/Translation/ExportVerilog/ExportVerilog.cpp#L1525) in a list of port assignments (in a module instantiation): if the last port is zero width, the previous port will end with a comma, which is a syntax error.

**Comment by lattner** [comment]
I just touched this code, I can fix this.

**Comment by lattner** [comment]
done in b932b27
