### ISSUE TITLE
[Arc] Test failing in nightly builds

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#4722]
https://github.com/llvm/circt/actions/runs/4262215066

The `Conversion/ConvertToArcs/convert-to-arcs.mlir` test is failing in several release configurations.

**Comment by maerhart** [comment]
Couldn't reproduce it locally, but there is an assert containing an expression with side-effects which should be avoided. So hopefully 7dd667052399c8f8bf3881fdd63291a495f3bda4 changes something.

**Comment by fabianschuiki** [comment]
Interesting. Only release builds with assertions off.

**Comment by fabianschuiki** [comment]
Thanks for the fix @maerhart! [Nightly seems to be fine again.](https://github.com/llvm/circt/actions/runs/4269871340)

**Comment by teqdruid** [comment]
Thanks for fixing this so promptly!
