### ISSUE TITLE
LLVM is not cached on GCC debug build

### ISSUE THREAD

**Issue by uenoku** [llvm/circt#4740]
https://github.com/llvm/circt/actions/runs/4289964745/jobs/7473505867
```
Post job cleanup.
/usr/bin/docker exec  9c490[2](https://github.com/llvm/circt/actions/runs/4289964745/jobs/7473505867#step:28:2)789be8[3](https://github.com/llvm/circt/actions/runs/4289964745/jobs/7473505867#step:28:3)0a2d7a920281d544091afe1f76a59a6aff8bf36ed179b67a9d2 sh -c "cat /etc/*release | grep ^ID"
/usr/bin/tar --posix -z -cf cache.tgz -P -C /__w/circt/circt --files-from manifest.txt

gzip: stdout: No space left on device
/usr/bin/tar: cache.tgz: Wrote only 61[4](https://github.com/llvm/circt/actions/runs/4289964745/jobs/7473505867#step:28:4)4 of 10240 bytes
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```
Previous issue https://github.com/llvm/circt/issues/4300

**Comment by teqdruid** [comment]
We probably build too much of LLVM. The regular builds are building 4250 files whereas the unified builds build 3566. If we want to keep building and caching LLVM separately, someone needs to identify all the necessary targets and compile only them.

Or we could add another corner from the integration tests (unified build) which covers GCC debug builds.

**Comment by uenoku** [comment]
I agree unified build would reduce the size but is it possible to cache only llvm libs in unified build?  

> Or we could add another corner from the integration tests (unified build) which covers GCC debug builds.

+1, similarly I'm wondering we can just move gcc+debug to nightly-integration tests and test gcc+release.

**Comment by teqdruid** [comment]
We want to have both a debug build and release build in the PR gates. Perhaps we should switch the order. Clang debug and gcc release?

We test a bunch of corners in the nightly, including gcc+debug. They're just all unified and use ccache instead of building all of mlir and caching all of it.

**Comment by uenoku** [comment]
> Perhaps we should switch the order. Clang debug and gcc release?

Sounds good idea. Testing here: https://github.com/llvm/circt/actions/runs/4306635035

**Comment by uenoku** [comment]
It passed 👍

**Comment by teqdruid** [comment]
Great! Merge it!
