### ISSUE TITLE
[FIRRTL] Memories Should Return Multiple Results

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#479]
The cleanup of FIRRTL instances to return multiple values in ded5bd2e396a84cc9e277573ce8e83d06b699bd4 and 938ad62122167d7498abef03d058e8d99a281c89 seems like a good candidate to cleanup how FIRRTL IR handles memories. Memories are "instance-like" and could return multiple values, one for each port instead of a single bundle representing everything.

This should help compact the IR representation by avoiding one level of subfield indirection.

**Comment by lattner** [comment]
+1!

**Comment by seldridge** [comment]
Closed via #538.
