### ISSUE TITLE
[PyCDE] when following guide to compile, git tags need to be fetched for "pip install" to work

### ISSUE THREAD

**Issue by VMois** [llvm/circt#5017]
When I am following https://circt.llvm.org/docs/PyCDE/compiling/#cloning-the-repo steps, fork, clone my fork, and try to compile and install PyCDE (`pip install`), the process fails with error:

```
assert version is not None
```

The error is due to missing git tags (they are not forked or cloned by default).

https://github.com/llvm/circt/blob/a3113e43772955052abf42f660da6df8971faf79/frontends/PyCDE/pyproject.toml#L21-L26

I managed to fix the error after adding this repo as a new remote (`upstream`) and doing `git fetch upstream --tags`. I think, it would be good to add this part to the documentation.

**Comment by teqdruid** [comment]
Thanks for the bug report!

**Comment by VMois** [comment]
I think one missing piece is the command `git remote add upstream git@github.com:llvm/circt.git`. The `upstream` remote doesn't automatically included if you clone your fork.

I can create a PR if it makes sense.

**Comment by teqdruid** [comment]
Serves me right for just blindly copy-pasting. Yes, please open a PR.
