### ISSUE TITLE
[CI] Windows build and test fails randomly

### ISSUE THREAD

**Issue by maerhart** [llvm/circt#5043]
I've had two seemingly random Windows CI failures on main recently (e7f306d and 15b43af). Both failing some firtool test (but a different one). Anyone a clue why that is? Is the build unstable or some UB somewhere?

**Comment by teqdruid** [comment]
We've had problems like this in the past. I suspect it's resource usage (i.e. out of memory or disk space).

**Comment by seldridge** [comment]
Closing this as the most recent maybe fix discussed in https://github.com/llvm/circt/issues/6193 is to bump the Windows runners. We can open another issue or revive this one in the future. However, I just want to keep the Windows build failures linked together and not have a bunch of ones open. We can always find them via search.
