### ISSUE TITLE
Sensitivity list for always* blocks could include expressions

### ISSUE THREAD

**Issue by darthscsi** [llvm/circt#508]
always* blocks should be emitted with names in the sensitivity list, not inline expressions.  Thus anything that might be in a sensitivity list must be output first to an assign statement and referenced by name.
consider:
```
%clk = %clk2+ %clk2
always posedge clk
```
will output something like
```
always @(posedge (clk2 + clk3)
```
which is wrong

**Comment by lattner** [comment]
Fixed in 87b572b, thanks!
