### ISSUE TITLE
[FIRRTL] Add Probes to Exporter

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#5122]
The FIRRTL exporter does not currently implement `probe` and associated reference type operations. Add support for these and make sure they round-trip correctly.

Consider the following:

```
circuit Foo:
  module Foo:
    output a: Probe<UInt<1>>
    output b: RWProbe<UInt<1>>

    wire x: UInt<1>

    define a = probe(x)
    define b = rwprobe(x)
```

This currently hits an unreachable condition if you try to export it:

```
# firtool Bar.fir -parse-only | circt-translate -export-firrtl
circuit Foo :
  module Foo :
    output a : all types should be implemented
UNREACHABLE executed at /Users/schuylere/repos/github.com/llvm/circt/lib/Dialect/FIRRTL/Export/FIREmitter.cpp:787!
```

**Comment by seldridge** [comment]
I fixed this except for `rwprobe` in https://github.com/llvm/circt/commit/50636dde95e2c959e737a2328099e7e9e1dc9cec.

**Comment by dtzSiFive** [comment]
Thanks for pushing on this!! :bowing_man: 

Few other ops for complete FIRRTL 2.0 probe/rwprobe import/export support:

* {force,release}{,_initial}
* ref.sub
* internalPaths? (ref statements)

**Comment by seldridge** [comment]
Added `rwprobe` in https://github.com/llvm/circt/commit/cd7f0d17e241c335fbd17d76804a1b94eff716b8 and https://github.com/llvm/circt/commit/e0d380299b60f489fd8216a332b7d3319995db32.

**Comment by dtzSiFive** [comment]
ref.sub handled in #5179 .

**Comment by dtzSiFive** [comment]
Force/release: 65546f4c61359041a3d1b07fe1851ed6492700b7
e0d380299b60f489fd8216a332b7d3319995db32
RefCast, RWProbeOp (RWProbe to local inner symbol), and improved Forceable support in: #5779.

I think everything is handled other than possibly ref statements/`internalPaths` (on external modules).

cc https://github.com/llvm/circt/issues/5205 for probe+emitter-related bug.

**Comment by seldridge** [comment]
Calling this done. 😉
