### ISSUE TITLE
[FIRRTL] Add Verifier for Memory Ops

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#519]
FIRRTL `MemOps` have haphazard verification split between helper methods `MemOp::getTypeForPortList` and parsing checks. All this should be rolled into an actual verifier.

I'm aware of the following checks that should be added:

- [ ] Memories with duplicate port names should error
- [ ] Memories with incorrect port types should error (e.g., a `MemOp::PortKind::ReadKind` should have a specific bundle format)
- [x] Depth must be >= 1 (f6b54073555e7a5a102b500111a9320d3eafbc42)
- [ ] Data type must be passive
- [ ] Data type cannot contain analog types
- [ ] Data type must the same for all ports
- [ ] Read latency must be non-negative
- [x] Write latency must be positive

**Comment by lattner** [comment]
+1
