### ISSUE TITLE
[RTL] Move all the combinational ops to a new 'comb' dialect

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#523]
What should the casing be on `comb`? All lower or `Comb`? I prefer all lower to save my wrists from the shift-c combo, but whatever.

**Comment by lattner** [comment]
comb for the dialect, and Comb for the filenames. "CombOps.cpp" etc.

**Comment by teqdruid** [comment]
Leave the module (and types?) in the RTL dialect.

**Comment by lattner** [comment]
Yep, makes sense.  We should move the combinational ops to the comb dialect then figure out what remains and where it should go.

**Comment by teqdruid** [comment]
I've started this effort here: https://github.com/llvm/circt/tree/rtl-comb

It's _way_ harder to extract only some ops.

**Comment by teqdruid** [comment]
It's compiling now, but I'm getting `LLVM ERROR: Building op `comb.constant` but it isn't registered in this MLIRContext` in many of the tests. I'm inserting `comb::CombDialect` [here](https://github.com/llvm/circt/blob/0f52a5a8f3d6a83644504090bc2440457aec2c7e/include/circt/InitAllDialects.h#L33). What else must I do?

**Comment by youngar** [comment]
@teqdruid If its the Conversion tests (something is converting TO the comb dialect), it has to be listed as a dependent dialect in the [ODS Pass declaration](https://github.com/llvm/circt/blob/main/include/circt/Conversion/Passes.td#L43)

**Comment by teqdruid** [comment]
It's not just the comb tests. The ones exhibiting this error are at a minimum:
```
  CIRCT :: Dialect/ESI/cosim.mlir
  CIRCT :: Dialect/FIRRTL/lower-types-errors.mlir
```

The others are namespace issues, which may or may not turn into this once I fix them.

**Comment by teqdruid** [comment]
Basically, any tests which run code with a `builder.create<comb::*>()`.

**Comment by teqdruid** [comment]
turns out those tests had `circt-translate` in them so I had to add the new comb dialect to its registration calls.

**Comment by youngar** [comment]
When building with `BUILD_SHARED_LIBS`, I'm getting a link error:
```
Undefined symbols for architecture x86_64:
  "circt::rtl::getBitWidth(mlir::Type)", referenced from:
      circt::comb::BitcastOp::verify() in CombOps.cpp.o
      circt::comb::__mlir_ods_local_type_constraint_Comb3(mlir::Operation*, mlir::Type, llvm::StringRef, unsigned int) in CombOps.cpp.o
```

I think this means we have to link Comb against RTL, but this is a circular dependency.

Have we considered moving all the RTL types (and `getBitWidth()`) over to the Comb dialect?

**Comment by teqdruid** [comment]
Chris and I have been having a lengthy discussion about where to put the 'type' ops over in #604. This is another good reason not to have inter-dialect dependencies. It's also a good reason to move `bitcast` over to the rtl dialect.

I'm not aware of any logical deps from rtl to comb. I'll try removing that from cmake and see what goes boom.

**Comment by teqdruid** [comment]
I forgot about the (near universal) dependency on `comb.constant`... It's only in one piece of code which I think only ESI uses.

**Comment by teqdruid** [comment]
I fixed that circular dep, but there are others (mostly in ESI) and missing deps in exportverilog.

BTW, if you're building dynamic libs to speed up your builds, I've found that using lld rather then ld *significantly* reduces build time of static builds. `-DLLVM_ENABLE_LLD=ON`.

**Comment by teqdruid** [comment]
See #641 for dynamic linking support fix

**Comment by lattner** [comment]
Yes, @teqdruid is right about the universal dependency on comb.constant.  [I think it should be](https://github.com/llvm/circt/issues/665) hoisted back up to rtl/hw dialects.

**Comment by teqdruid** [comment]
If we were to move the bitcast op back as well, I don't think there'd be any dependencies between rtl and comb.

**Comment by lattner** [comment]
Where does bitcast get cross referenced?

**Comment by teqdruid** [comment]
Bitcast uses `getBitWidth()` in the RTL dialect. I think that's the only reference between the two dialects in either direction at this point.

**Comment by lattner** [comment]
Ok yeah, it is fine for comb/SV to call into RTL, just not the other way around.
