### ISSUE TITLE
[RTL/SV] Move all the inout stuff to the SV dialect

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#524]
This is an issue to discuss this topic.

**Comment by teqdruid** [comment]
Arguments in favor:
 - It complicates the logic necessary in the RTL dialect. (See all the exceptions/look through logic.)
 - It (currently) has structure/syntactic semantics. The RTL dialect should be value semantics.
 - I get the feeling that this is a poorly understood concept in terms of generic/higher-level modeling. It is a well understood concept in SystemVerilog. There _may_ be a place for it in the RTL dialect once we get a handle on how it should be modeled.

**Comment by lattner** [comment]
Yep, seems like the right thing to do to me.  inout type and wire should both move to SV.  This will also force us to figure out the type system layering issues.

**Comment by lattner** [comment]
Fixed in 7ddfc3e.

**Comment by teqdruid** [comment]
Great! Thanks!
