### ISSUE TITLE
Build problem for FIRRTLTypeInterfaces.h

### ISSUE THREAD

**Issue by wky17** [llvm/circt#5258]
I tried to build circt project according to README.md like:
```
$ cd circt
$ mkdir build
$ cd build
$ cmake -G Ninja .. \
    -DMLIR_DIR=$PWD/../llvm/build/lib/cmake/mlir \
    -DLLVM_DIR=$PWD/../llvm/build/lib/cmake/llvm \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DCMAKE_BUILD_TYPE=DEBUG \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
$ ninja
$ ninja check-circt
$ ninja check-circt-integration # Run the integration tests.
```

but there is an error in _FIRRTLTypeInterfaces.h_, which is cannot find file _FIRRTLTypeInterfaces.h.inc_ like this:
![29141684982710_ pic](https://github.com/llvm/circt/assets/63497196/342301b0-981b-4314-847d-99c0f522eb6e)
I've check there are *.h.inc files under circt/build/include/circt/Dialect/FIRRTL, but there is definitely no this one. I guess it should be generated during build precess, but I can't figure out why it's not there and can't execute the code.

The generated files under this dir is like:
things for chirrtl and the following
<img width="319" alt="截屏2023-05-25 11 32 43" src="https://github.com/llvm/circt/assets/63497196/6e2fd2af-5f2e-47d8-9773-6e8b753f7ba9">

**Comment by dtzSiFive** [comment]
I'm not sure what this was about (maybe some include path missing a dependency?) but the `FIRRTLTypeInterfaces.h` was dropped as of earlier today (#5262) so nothing to fix here anymore, closing.
