### ISSUE TITLE
ESI/Capnp CMake error

### ISSUE THREAD

**Issue by maerhart** [llvm/circt#5264]
I updated my local CIRCT to current main (775725e13441dafef71b0e90ef15a0c4a2e2a3c3) and because I don't have CapNProto installed, CMake complained during configuration and suggested to use `CAPNP_DISABLE=1` which I did, but then the following error popped up. Am I doing something wrong or did I miss something?
```
CMake Error at lib/Dialect/ESI/CMakeLists.txt:79 (add_library):
  Cannot find source file:

    FILE_SET

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
```

As a workaround I commented out the following lines: https://github.com/llvm/circt/blob/31770e1fdd70898c1616aa81ad4ad36863157e9b/lib/Dialect/ESI/CMakeLists.txt#L114-L116

**Comment by teqdruid** [comment]
Shit. FILE_SET is a feature of a newer version of CMake. It's gated on that version for CAPNP builds, but those aren't CAPNP files... @mikeurbach 

I'll move them as a mitigation step.

**Comment by maerhart** [comment]
Thanks!
