### ISSUE TITLE
[FIRRTL] Strip Portless Memories during Parsing

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#531]
- Remove FIRRTL memories that have no ports during parsing
- Require that memories have a type (because memories now must have at least one port)

**Comment by lattner** [comment]
I'm happy to do this now but I don't want to conflict with your other patch that is outstanding, just lemme know what you prefer.

**Comment by seldridge** [comment]
Yeah, sorry, this should be pretty easy to implement, but it would be easier to wait for #488 to re-land. Thanks!

**Comment by lattner** [comment]
Happy to wait, no problem

**Comment by lattner** [comment]
Done in d1a3e10, thanks!
