### ISSUE TITLE
[FIRRTL] crash, need getFieldName (and friends?) support for enums

### ISSUE THREAD

**Issue by dtzSiFive** [llvm/circt#5324]
Following input crashes due to getFieldName not being supported (used to report error in InferWidths):

```firrtl
circuit NoWidthEnum:
  module NoWidthEnum:
    output o : {| Some : UInt, None |}
```

**Comment by youngar** [comment]
https://github.com/llvm/circt/pull/5439 fixes `getFieldName`.  I was looking at other helpers we are missing support for, and notably we are missing support in `getValueByFieldID`, which is used for GrandCentral and WireDFT.  I don't think that it makes sense for these passes to target a specific variant of an EnumerationType, it should probably be limited to targeting the enumeration as a whole.  We should probably enforce that limitation in how we attach annotations.

**Comment by youngar** [comment]
Opened an issue for the above comment here: https://github.com/llvm/circt/issues/5441
