### ISSUE TITLE
[Seq] Write motiving rationale for future sequential dialect

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#539]
Should include the definitions from the meeting notes.

**Comment by lattner** [comment]
Almost done!

**Comment by mortbopet** [comment]
Based on https://circt.llvm.org/docs/Dialects/Seq/RationaleSeq/ this seems like it's done?

**Comment by teqdruid** [comment]
Ha! This is an old one. Thanks for the backlog grooming!
