### ISSUE TITLE
Does the LLVM license exception apply to circt

### ISSUE THREAD

**Issue by shawnl** [llvm/circt#54]
It doesn't appear that circt is under the llvm license---i.e. the GPLv2 exception.

**Comment by shawnl** [comment]
Considering that this is a LLVM incubator project, I think the intent is for the license to be the same as LLVM, but all the focus has just been on the code so no-one noticed this discrepency. We should should fix it now :).

**Comment by lattner** [comment]
Agreed, this is just an oversight.  Please feel free to check in a clarification here.  Thanks!
