### ISSUE TITLE
[Python] Nightly wheel builds not uploading

### ISSUE THREAD

**Issue by mikeurbach** [llvm/circt#5431]
@rsetaluri FYI, it looks like the nightly triggers are running the build wheel jobs, but they are not matching the step that actually uploads to PyPI. Here's the latest: https://github.com/llvm/circt/actions/runs/5322294711/jobs/9638544061.

Also note that once this is fixed, we will run into #5420 .

**Comment by rsetaluri** [comment]
@mikeurbach thanks for raising this (apologies for letting this sit for so long...)

I'm guess in the following line that `github.event_name == 'cron'` is not the right condition:

https://github.com/llvm/circt/blob/7f9ed020e1be3e62b8f0dfc837f66fe5c56931fb/.github/workflows/uploadWheels.yml#L59

From looking at the docs it's not immediately clear what the right condition is. Perhaps `github.event == 'schedule'`? (We could probably further refine it with `&& github.event.schedule == '0 12 * * *'`.)

**Comment by rsetaluri** [comment]
Here, I see `github.event_name == 'schedule'`:

https://github.com/simonw/til/blob/main/github-actions/different-steps-on-a-schedule.md

I'll give that a try

**Comment by rsetaluri** [comment]
Closed by #5623

**Comment by mikeurbach** [comment]
Thanks. Does the macos upload actually work? I was under the impression it fails because of https://github.com/llvm/circt/issues/5420

**Comment by rsetaluri** [comment]
> Thanks. Does the macos upload actually work? I was under the impression it fails because of #5420

I'm guessing #5420 still keeps this from working. Working on addressing that right now - look out for a PR shortly!

**Comment by rsetaluri** [comment]
@mikeurbach confirming #5623 worked, as we have a nightly pre-release on pypi for manylinux: https://pypi.org/project/circt/1.48.1.dev15/.

The macos releases are still blocked by #5420 (hopefully solved by #5628) and possibly also #5634.
