### ISSUE TITLE
[Documentation] Confusing getting started documentation

### ISSUE THREAD

**Issue by ManelMCCS** [llvm/circt#5545]
There are two links about getting started:

https://circt.llvm.org/docs/GettingStarted/
https://circt.llvm.org/getting_started/

Futhermore, the in the home page the CIRCT diagram don't have any labels and have in the getting started documentations. (the first one).

**Comment by mortbopet** [comment]
Attempted fix [here](https://github.com/llvm/circt-www/pull/16).

**Comment by mortbopet** [comment]
https://circt.llvm.org/getting_started/ now points to https://circt.llvm.org/docs/GettingStarted/
