### ISSUE TITLE
[Nightly] Clang build out of space

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#5621]
![image](https://github.com/llvm/circt/assets/1498080/0f868f58-1c52-4f9b-a9f1-a7635f958ad3)

https://github.com/llvm/circt/actions/runs/5587119082/jobs/10212043774

[ON, OFF, Debug, clang, clang++](https://github.com/llvm/circt/actions/runs/5587119082/jobs/10212043774#logs)

**Comment by seldridge** [comment]
Ugh... I'll try restarting this to just see if it was possibly transient. Otherwise, this may be tricky to fix.

**Comment by teqdruid** [comment]
They've failed a few nights in a row...

**Comment by dtzSiFive** [comment]
Should be fixed via #5692, :crossed_fingers: !
