### ISSUE TITLE
[Calyx] Return type of `getBound()` in  `CalyxLoweringUtils`

### ISSUE THREAD

**Issue by calebmkim** [llvm/circt#5691]
Currently, `getBound()` [returns](https://github.com/llvm/circt/blob/10cae4c30bf24cbc3785414635b30788bf73cb81/include/circt/Dialect/Calyx/CalyxLoweringUtils.h#L142) a `std::optional<uint64_t>`. 

I currently have a PR (#5655) that uses `mlir`'s `constantTripCount()` function for `getBound`. One small issue is that `constantTripCount()` for some reason returns a `std::optional<int64_t>` (that is, signed and not unsigned). As I say in the PR, this is a bit odd, since intuitively, the trip count can never be negative, although there may be a good reason for this choice. 

We may want to consider changing `getBound` to return `std::optional<int64_t>` to align with `constantTripCount`'s choice? 

Another option is to a) ignore this discrepancy since it likely won't come up or b) do a different way of computing the trip count, although neither of these necessarily choices feel like best practice.

**Comment by mikeurbach** [comment]
I guess it's reasonable to use an int64_t to align with the helper in MLIR for now.
