### ISSUE TITLE
[Feature Request] Release CIRCT and MLIR static library binaries

### ISSUE THREAD

**Issue by SpriteOvO** [llvm/circt#5814]
chipsalliance/chisel#3466 implements a new converter directly input Chisel IR from Scala to CIRCT by Java Panama framework.

Panama requires linking against CIRCT and MLIR libraries to work. For local, we can compile CIRCT ourselves, but for the CI test of Chisel, I think the best solution is download the binaries from somewhere, e.g. from the GitHub Release Page.

We can modify the CI script to compiling and uploading the static libraries, just like the `firtool` binary now.

**Comment by rachitnigam** [comment]
I want to +1 this as well. Our specific use case is running CIRCT integration tests with the native Calyx compiler: https://github.com/cucapra/calyx/issues/1608
