### ISSUE TITLE
StandardToHandshake.cpp ignoring result of rewriteAffineFor

### ISSUE THREAD

**Issue by lattner** [llvm/circt#583]
I get this warning from the build:

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp:1454:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    rewriteAffineFor(newFuncOp, rewriter);
    ^~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~

indeed, this can fail when the affine for is too complicated.  The caller should handle the error somehow.

**Comment by mikeurbach** [comment]
I was going to take a look at re-working that function soon anyway, so I can update it for now to handle the failure.

**Comment by lattner** [comment]
thx!
