### ISSUE TITLE
[RTL] Remove rtl.andr/orr, replace xorr

### ISSUE THREAD

**Issue by lattner** [llvm/circt#598]
We should eliminate rtl.andr/orr with the equivalent comparisons: `andr(x)` -> `x == -1` and replace  `orr(x)` -> `x != 0`.  This eliminates the number of canonicalization patterns we need to implement and reduces redundancy in the IR.

Given this, I think we should rename `rtl.xorr(x)` -> `rtl.parity(x)` but keep the same semantics.

**Comment by youngar** [comment]
@prithayan will be working on this

**Comment by prithayan** [comment]
Fixed in the above PRs, 653, 652 and 642

**Comment by lattner** [comment]
nice work, thank you!
