### ISSUE TITLE
[FIRRTL] Add option to report parse+verifier timing

### ISSUE THREAD

**Issue by youngar** [llvm/circt#608]
Firtool has a nice option to print the timing of each pass, `--pass-timing`, but it would be nice to have timers that encompass more than just the passes.  I would like an option to report the time taken to parse a firrtl file and construct the initial IR.

**Comment by lattner** [comment]
Yeah this would be very nice!

**Comment by lattner** [comment]
The verifier is also a significant amount of time, we should add a timer for it as well.
