### ISSUE TITLE
[ExportVerilog] Name conflicts with other module names

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#625]
The name generator in ExportVerilog.cpp doesn't check for conflicts with module names or other symbols. This is technically allowed but I don't think we should allow the name auto-uniquer to do it.

**Comment by lattner** [comment]
Is this a style thing?  I think they are in a different namespace.  Can you give an example of what you're concerned about?

**Comment by teqdruid** [comment]
It’s just a style thing and I think it contributes to readability. I’ve got
a small example in the test for the PR I submitted on this.

**Comment by lattner** [comment]
xref https://github.com/llvm/circt/pull/770  @fabianschuiki

**Comment by lattner** [comment]
I thin kthis is done.
