### ISSUE TITLE
[SV] Split sv.ifdef into two different operations

### ISSUE THREAD

**Issue by lattner** [llvm/circt#627]
It came up in a discussion yesterday that sv.ifdef should be split into the different nodes, one that is a `ProceduralRegion` that can be used in an always block, and one that is a graph region that can be used in a top level of an rtl.module.

This will allow us to build better assertions, e.g. check that a fwrite only occurs in `ProceduralRegion`'s

**Comment by teqdruid** [comment]
Why not do a recursive check that ops are in a procedural region?

**Comment by lattner** [comment]
Splitting it this way just makes it simpler to implement the checks, and makes them local.

**Comment by teqdruid** [comment]
Fair enough. I just worry about havIng to split a bunch of ops in this
manner, but this is probably the practical choice if it’s just one or a
small number.

**Comment by lattner** [comment]
Yep, I think it is just ifdef

**Comment by lattner** [comment]
I'm going to take this, as this will simplify other things in my path

**Comment by lattner** [comment]
Done in 906690b
