### ISSUE TITLE
LLVM pointers without inner type cause stores to disappear in LLHD lowering

### ISSUE THREAD

**Issue by fabianschuiki** [llvm/circt#6326]
An MLIR bump that removed the inner type from `!llvm.ptr` causes a few `llvm.store`s to disappear in the LLHD tests:

https://github.com/llvm/circt/pull/6322/files/569fa19148fe26d3d3ef742518ff9ccafd841447#r1366809786

This doesn't seem to affect simulations. Investigate if this is benign.

**Comment by maerhart** [comment]
Since `LLHDToLLVM.cpp` is removed now, this shouldn't be an issue anymore.
