### ISSUE TITLE
N-level nested symbol tables, the Inner* infra, and upstreaming

### ISSUE THREAD

**Issue by mortbopet** [llvm/circt#6330]
In the process of addressing #6294 by attempting to move it over to the Inner* infra, we've encountered a case of requiring support for two levels of nested symbol tables. That is, we have an `ibis.class` op - which is nested under `builtin.module` and defines an `InnerSymbolTable` - that may have `ibis.container` ops inside, which itself defines a `NestedSymbolTable`.

While i still have some experimenting to do, I'm opening this issue to have a place for capturing discussion about the "canonical" way of/how we want to support arbitrarily-nested symbol tables. This seems apt if we're planning on eventually upstreaming Inner* stuff, wherein i cannot imagine that only supporting a single level of nesting is acceptable.

Things to discuss:
* How is a symbol table hierarchy expressed?
  * In the current state, the most obvious representation would be a sequence of ops that inherit both `InnerSymbolTable` and `InnerRefNamespace`.
 * How is a symbol table hierarchy verified?
   * I.e. how can we verify operations that reach across/through multiple levels of symbol tables? Currently, an `InnerSymbolTableCollection` is generated for the top-level `InnerSymbolTable`s (e.g. a set of `hw.module`s) and then the IR is **walked** for `InnerRefUserOpInterface`s and these are verified with the set of symbol tables (https://github.com/llvm/circt/blob/main/lib/Dialect/HW/InnerSymbolTable.cpp#L222-L242). This thus only allows for a single, top level of symbol tables.
   * A change could be that `InnerRefNamespace` is only present for the top-level operation, and then **any** operation at any level below that top-level op can implement `InnerSymbolTable`, as long as there is _some_ operation in its parent hierarchy that is an `InnerRefNamespace`. Verification would then likewise walk the hierarchy _from_ the `InnerRefNamespace` and build the symbol table collection based on the symbol table hierarchy.

**Comment by teqdruid** [comment]
Just reviewed the ODM discussion, and we agreed that we don't need nested symbol tables after all. The nested innersymbols just have to be unique.
