### ISSUE TITLE
[CAPI][FIRRTL] CAPI nightly-integration test failure

### ISSUE THREAD

**Issue by uenoku** [llvm/circt#6473]
Commit: https://github.com/llvm/circt/commit/3b7d738056ef9aa0dba6858b11559ad39c988d6d

```
Failed Tests (1):
  CIRCT :: CAPI/firtool.c
```

https://github.com/llvm/circt/actions/runs/7046140623/job/19177333781

**Comment by SpriteOvO** [comment]
I'm handling it.

**Comment by uenoku** [comment]
Thanks!
