### ISSUE TITLE
[ESI] Nightly Failure

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#6653]
There was a nightly failure seen in ESI here: https://github.com/llvm/circt/actions/runs/7799293590/job/21269799065#step:8:337

This may be related to this change: https://github.com/llvm/circt/commit/2d1df42ac326e3a568f67b29456524180cc1e64c#diff-cd3841e90b3c5aa54afa73e68ef831f8f5e2cf50390547b1578229871dd1c83bR339

@teqdruid: Could you poke at this?

**Comment by teqdruid** [comment]
Saw that. Was gonna look into it today. I think I know the cause.

**Comment by teqdruid** [comment]
I'm pretty sure this resolves the failure (which would have been non-deterministic).
