### ISSUE TITLE
[Documentation] circt.llvm.org has not been updated

### ISSUE THREAD

**Issue by uenoku** [llvm/circt#6722]
The last success was November. Seems like permission issue https://github.com/llvm/circt-www/actions/runs/7515748531/job/20460035983

**Comment by mikeurbach** [comment]
Should hopefully be fixed by https://github.com/llvm/circt-www/commit/b292d5a218701802b6575c5a93386a5dcbf16c93. We had to set something similar in the CIRCT repo, and mlir-www has the same: https://github.com/llvm/mlir-www/blob/3beedbbb2dfee495309c2a828588153177cd8ac3/.github/workflows/main.yml#L22

**Comment by mikeurbach** [comment]
Looks like the Deploy step went through: https://github.com/llvm/circt-www/actions/runs/7997222306/job/21841254103

**Comment by uenoku** [comment]
Thanks Mike!
