### ISSUE TITLE
[Comb] Allow operand and result of SExtOp to have the same width

### ISSUE THREAD

**Issue by uenoku** [llvm/circt#692]
Currently operations like ` %0 = comb.sext %a : (i1) -> i1` are prohibited by the verification of `SExtOp`. 
I think it would be more useful to allow an operand and result to have the same width and eliminate sext in canonicalization.

**Comment by lattner** [comment]
Yes, I can see how this is useful, particularly with the createAndFold pattern that MLIR has. Go for it, thank you!
