### ISSUE TITLE
[FIRRTL][LowerTypes]Node cannot be declared with a flip field?

### ISSUE THREAD

**Issue by wky17** [llvm/circt#6939]
when I write a Firrtl program like this:
<img width="799" alt="截屏2024-04-22 13 29 21" src="https://github.com/llvm/circt/assets/63497196/2694c674-a74a-4ce3-8a94-185cee3226f3">
where node a would be a bundle type with flip field, there is an error by firtool in the LowerTypes pass:
<img width="848" alt="截屏2024-04-22 13 30 33" src="https://github.com/llvm/circt/assets/63497196/ce4ab2d6-9ad3-4106-a70c-070de918a1ca">
is this means that a node component cannot be declared with a flip field? I think it's not so clear in the specification.

**Comment by uenoku** [comment]
Yes node cannot have a flip. I agree that firrtl-spec is slightly unclear but firrtl-spec says nodes must be sources in a section Connection>Flow. 
```
If the expression is an identifier, we look at the kind of the circuit component the identifier refers to:

* Nodes are sources.
```
