### ISSUE TITLE
[FIRRTL] Crash in LowerClasses with "corrupted double-linked list"

### ISSUE THREAD

**Issue by mikeurbach** [llvm/circt#7099]
I just observed this on main on a large internal design. I haven't had a chance to reduce and example yet. It appears be non-deterministic, and it also appears to go away with multithreading disabled.

**Comment by mikeurbach** [comment]
Just a stab in the dark here, is it perhaps not safe to update this map in parallel?

https://github.com/llvm/circt/blob/e71ccb85f7b842c5020e5e4f1e2507582335baab/lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp#L665

**Comment by uenoku** [comment]
It's pre-allocated before so i believe it's fine.

**Comment by uenoku** [comment]
Done by https://github.com/llvm/circt/pull/7102
