### ISSUE TITLE
Represent modules in RTL Dialect

### ISSUE THREAD

**Issue by amaleewilson** [llvm/circt#72]
Currently relying on FIRRTL circuit and module. RTL Dialect should have its own module ops.

**Comment by amaleewilson** [comment]
Step two: 
- rtl.instance op take inputs as arguments and produce outputs as results. 'inout' should be handled like inputs for rtl.instance.
- rtl.module to represent outputs as operands to the "done" op (which can then be renamed to return or something) instead of being BB operands that get connected to. inout arguments should be modeled as bb arguments like inputs, and should have connects to them.

**Comment by lattner** [comment]
I think this is now done.  The other changes are tracked in other issues.  Thanks!
