### ISSUE TITLE
[SV] Canonicalize sv.if blocks with empty then's into inverted conditions

### ISSUE THREAD

**Issue by lattner** [llvm/circt#721]
It is a generally good idea to turn: `sv.if %cond {} else { stuff}` into `%inverted = comb.xor %cond, 1; sv.if %inverted { stuff}`.

This allows merging the invert into conditions etc.

**Comment by uenoku** [comment]
I think it is neccesary to have SV->Comb dependency to perform this operation. 
Is it fine?

**Comment by lattner** [comment]
Yeah I think this is ok.  SV will be an uber dialect that depends on a lot of other things, incl `seq` when it exists.  We should make sure that comb and rtl don't depend in it though.
