### ISSUE TITLE
[Seq] Unify HLMem and FIRMem

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#7211]
When FIRMem got merged, the idea was to rapidly unify it with the existing HLMem. They are very similar. That hasn't happened yet.

**Comment by mortbopet** [comment]
possible duplicate of https://github.com/llvm/circt/issues/5463... but thank you for bumping the issue 👍.

**Comment by teqdruid** [comment]
Yep, this is a dup. GH issues search isn't great.
