### ISSUE TITLE
[ESI] ESI runtime relies on CIRCT-defined CMake variables

### ISSUE THREAD

**Issue by mortbopet** [llvm/circt#7254]
E.g.
https://github.com/llvm/circt/blob/20e08c092c67adf20d6b4114d06e45d5d8dc4965/lib/Dialect/ESI/runtime/cosim/CMakeLists.txt#L21-L24

relies on `CIRCT_TOOLS_DIR`. When ESI Runtime is built out-of-tree, `CIRCT_TOOLS_DIR` is undefined, resulting in an attempted copy of `esi-cosim.py` to `/esi-cosim.py`, which is illegal.

Some possible offending locations:
- https://github.com/llvm/circt/blob/5950674a5f32b31820fc734b0da4aa549a3b9c68/lib/Dialect/ESI/runtime/cosim/MtiPliStub/CMakeLists.txt#L3
- https://github.com/llvm/circt/blob/20e08c092c67adf20d6b4114d06e45d5d8dc4965/lib/Dialect/ESI/runtime/cosim/CMakeLists.txt#L24
- https://github.com/llvm/circt/blob/20e08c092c67adf20d6b4114d06e45d5d8dc4965/lib/Dialect/ESI/runtime/cosim/CMakeLists.txt#L29

**Comment by teqdruid** [comment]
Huh. I could've sworn that I built this out of tree at some point. I'll fix on top of #7241 .
