### ISSUE TITLE
[hwarith] Shouldn't ICmpOp result be `i1`?

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#7406]
The result of a `hwarith.icmp` is always `ui1`. Shouldn't it be `i1`? Logically, the result is a boolean which doesn't have signedness semantics. What was the original rationale for this (since it seems like a very intentional decision)?

**Comment by teqdruid** [comment]
@mortbopet @jopperm

**Comment by jopperm** [comment]
Hmm, I don't remember whether we discussed that specifically (CC: @7FM). I think the idea was that `hwarith`'s operations would work on MLIR's signed/unsigned types, with the `cast` operation being the defined transition point to/from the signless world, so `ui1` was the natural choice. But yeah, you can't do much with the result in the dialect other than casting to `i1`...

**Comment by teqdruid** [comment]
Ok. Ima change it then.
