### ISSUE TITLE
[FIRRTL] Does 'regreset' in CHIRRTL have the corresponding calss in firrtl.ir?

### ISSUE THREAD

**Issue by zhangkanqi** [llvm/circt#7601]
Hi, 
I have a .fir file with FIRRTL version 3.3.0, which has  a `regreset` statememt as follows:
```firrtl
 regreset pendingld_last_REG : UInt<1>, clock, reset, UInt<1>(0h0) @[utility/src/main/scala/utility/ClockGatedReg.scala 30:20]
```

Now, I want to match this statement like Connect:
```scala
Statement match {
  case conn: Connect => println(conn.serialize)
  case RegReset?
}
```

So I wonder know does 'regreset'  have the corresponding calss in firrtl.ir(Like `connect` in CHIRRTL , `Connect` in firrtl.ir )? I haven't found that so far.

Looking forward to your reply :)

**Comment by uenoku** [comment]
There is regreset op https://github.com/llvm/circt/blob/7db6951f021e975c1518b22ee92b9402f93d124b/include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td#L527

**Comment by uenoku** [comment]
Probably your link is referring to very old version. I think you can find the corresponding Chisel class here https://www.chisel-lang.org/api/latest/firrtl/ir/DefRegisterWithReset.html
