### ISSUE TITLE
[MooreToCore] Support assert, assume, cover ops

### ISSUE THREAD

**Issue by fabianschuiki** [llvm/circt#7630]
Add conversion patterns from `moore.{assert,assume,cover}` to the corresponding `verif.*` op in MooreToConv. Consider rejecting deferred assertions for now. https://chipsalliance.github.io/sv-tests-results/?v=circt_verilog+16.2+assert_test

**Comment by mingzheTerapines** [comment]
@fabianschuiki  
https://chipsalliance.github.io/sv-tests-results/?v=circt_verilog+16.2+assert_test
and
https://chipsalliance.github.io/sv-tests-results/?v=circt_verilog+16.4+assert0_test
all cleared, happy to see this issue could be closed =)

**Comment by fabianschuiki** [comment]
Very exciting :partying_face:! Thanks for adding support for this in #7681 :smile_cat:

**Comment by fabianschuiki** [comment]
Also looks like we're up to 42% of tests passing now: https://chipsalliance.github.io/sv-tests-results/history :tada:
