### ISSUE TITLE
Implement Scala FIRRTL Compiler Constant Propagation

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#804]
Add a pass to the FIRRTL Dialect that implements Scala FIRRTL Compiler-style constant propagation. 

The tests in the Scala FIRRTL Compiler should provide guidance here: https://github.com/chipsalliance/firrtl/blob/master/src/test/scala/firrtlTests/ConstantPropagationTests.scala

**Comment by fabianschuiki** [comment]
Reminder: We should replace the current uses of `constFoldBinaryOp` with a custom function that handles zero-/sign-extension to a unified bit width, depending on the result type. Currently `constFoldBinaryOp` only folds constants of identical type, but FIRRTL allows for a mix-and-match.

**Comment by dtzSiFive** [comment]
Okay to close, with our current IMCP implementation + folders?

**Comment by fabianschuiki** [comment]
Yeah I think we cover this :+1:
