### ISSUE TITLE
[comb] Still missing lots of constant folders

### ISSUE THREAD

**Issue by lattner** [llvm/circt#820]
For example, this should fold but doesn't yet:

```
    %c13274935_i30 = rtl.constant 13274935 : i30
    %c-411106406_i30 = rtl.constant -411106406 : i30
    %60 = comb.divu %c13274935_i30, %c-411106406_i30 : i30
```

**Comment by Ayushsunny** [comment]
> For example, this should fold but doesn't yet:
> 
> ```
>     %c13274935_i30 = rtl.constant 13274935 : i30
>     %c-411106406_i30 = rtl.constant -411106406 : i30
>     %60 = comb.divu %c13274935_i30, %c-411106406_i30 : i30
> ```

I would like to work on this issue

**Comment by lattner** [comment]
Cool, please do!

**Comment by Ayushsunny** [comment]
> Cool, please do!

So, what exact I have to do @lattner sir ? as I am a new to open source I need some help before start contributing

**Comment by Ayushsunny** [comment]
? @lattner

**Comment by lattner** [comment]
Hi @Ayushsunny.  I'm sorry, but I don't have the ability to give you a full development tutorial here.  I'd recommend that you read some of the MLIR tutorials and look for other examples to learn from how they worked.

**Comment by uenoku** [comment]
Closed by https://github.com/llvm/circt/commit/27c9e6c94d1a7887a8288b7a4a6823719d797215
