### ISSUE TITLE
Remove unnecessary terminator instructions

### ISSUE THREAD

**Issue by lattner** [llvm/circt#822]
`sv.if`, `firrtl.circuit` and many other operations have terminators (e.g. `sv.yield`) that only exist to make MLIR happy.  These things waste memory and make iterator traversals more annoying.  

Recently @joker-eph landed a [new feature](https://llvm.discourse.group/t/rfc-making-terminator-optional-for-single-block-graph-regions/2997) in MLIR trunk that eliminates the need for this.  We should adopt it to clean things up.

**Comment by youngar** [comment]
closed by https://github.com/llvm/circt/pull/923
