### ISSUE TITLE
rtl.array_create MLIR syntax has needless parens around element type

### ISSUE THREAD

**Issue by lattner** [llvm/circt#866]
We currently have something like this:

```
%arr = rtl.array_create %arg0, %arg0 : (i8)
```

But could/should have:

```
%arr = rtl.array_create %arg0, %arg0 : i8
```

**Comment by Ayushsunny** [comment]
Are you talking about this line sir @lattner ?
https://github.com/llvm/circt/blob/94ff0a17647652545f35975c545921dadd71c44b/test/Dialect/RTL/basic.mlir#L121

**Comment by lattner** [comment]
Yes, the parser/printer logic for array_create needs to be updated to eliminate the need for it, then the testcases updated

**Comment by Ayushsunny** [comment]
So, @lattner I have to change this https://github.com/llvm/circt/blob/94ff0a17647652545f35975c545921dadd71c44b/test/Dialect/RTL/basic.mlir#L121

to this `%0 = rtl.array_create %arg0, %arg0 : i8` .

I'm going right sir?

**Comment by lattner** [comment]
Yes, that is the goal

**Comment by skanjani** [comment]
Hi @Ayushsunny, I think you need to change the printer/parser method define in the Tablegen file (.td) - https://github.com/llvm/circt/blob/main/include/circt/Dialect/RTL/RTLAggregates.td#L18.

.mlir files are the test cases to check the functionality of these Op definitions. 

You can read more about Tablegen syntax here -https://mlir.llvm.org/docs/OpDefinitions/.
.mlir file syntax define here -https://mlir.llvm.org/docs/LangRef/.

**Comment by Ayushsunny** [comment]
> Hi @Ayushsunny, I think you need to change the printer/parser method define in the Tablegen file (.td) - https://github.com/llvm/circt/blob/main/include/circt/Dialect/RTL/RTLAggregates.td#L18.
> 
> .mlir files are the test cases to check the functionality of these Op definitions.
> 
> You can read more about Tablegen syntax here -https://mlir.llvm.org/docs/OpDefinitions/.
> .mlir file syntax define here -https://mlir.llvm.org/docs/LangRef/.

Okay, Thank you so much sir

**Comment by Ayushsunny** [comment]
Hello @lattner Can you explain me this please. I am bit confused
