### ISSUE TITLE
implement shift operations

### ISSUE THREAD

**Issue by drom** [llvm/circt#9]
The binary shift operation shall perform:
* [ ] `shru` - shall shift their left operand to the right by the number of bit positions given by the right operand. Fill the vacated bit positions with zeros
* [ ] `shrs` - shall shift their left operand to the right by the number of bit positions given by the right operand. Fill the vacated bit positions with the value of the most significant 
* [x] `shl` - shall shift their left operand to the left by the number of bit positions given by the right operand.

**Comment by lattner** [comment]
Is this done now?

**Comment by lattner** [comment]
this is done.
