### ISSUE TITLE
[FIRRTL]`is invalid` not working for registers in the parser

### ISSUE THREAD

**Issue by youngar** [llvm/circt#942]
Setting registers to invalid is not working correctly in the parser.  
```firrtl
; ./bin/circt-translate --import-firrtl  ./test.fir
circuit F :
  module F :
    input clock : Clock
    
    ; output port works as expected
    output out : UInt<1>
    out is invalid
    
    ; register is never set to invalid
    reg r : UInt<1>, clock
    r is invalid
```

```mlir
firrtl.circuit "F"  {
  firrtl.module @F(%clock: !firrtl.clock, %out: !firrtl.flip<uint<1>>) {
    %0 = firrtl.invalidvalue : !firrtl.uint<1>
    firrtl.connect %out, %0 : !firrtl.flip<uint<1>>, !firrtl.uint<1>
    %r = firrtl.reg %clock  : (!firrtl.clock) -> !firrtl.uint<1>
    %1 = firrtl.invalidvalue : !firrtl.uint<1>
  }
}
```

This is because the register value has a passive type, and we do not emit connects to invalid when the LHS is passive.  Switching the parser to emit a connect when the LHS is passive makes the following test fail. This test is represented in the repo [here](https://github.com/llvm/circt/blob/main/test/Dialect/FIRRTL/parse-basic.fir#L112).

```firrtl
circuit F:
  module F:
    input a : UInt<1>
    a is invalid
```
```
./test2.fir:4:7: error: 'firrtl.connect' op connection destination must be a non-passive type or a duplex value
    a is invalid
      ^
./test2.fir:4:7: note: see current operation: "firrtl.connect"(%a, %0) : (!firrtl.uint<1>, !firrtl.uint<1>) -> ()
```

Could this be fixed with the coming changes to flip canonicalization?

**Comment by seldridge** [comment]
> Could this be fixed with the coming changes to flip canonicalization?

Probably.

Did you try checking if the LHS is duplex, first, and doing the assign differently in that case?

I think this is generally the problem of FIRRTL dialect using flip as a proxy for direction and flow, but representing ports/instances _backwards_ from how it represents reg/wire. An input port is "un-flipped" and "source-like". An output port is "flipped" and "sink-like" (except when you can also read from it). For connection, all that really matters is the LHS. If a LHS is un-flipped, it's a "sink-like" normal connect. If the LHS is flipped, then it's "source-like" and the connection is reversed. 

_This is the backwards convention from ports/instances._

The SFC keeps `is invalid` around and lowers that during connection expansion by connecting to anything that makes sense using the rules above (but which FIRRTL dialect needs to reverse for ports/instances vs. wires/registers).
