### ISSUE TITLE
https://circt.llvm.org/ should have a pointer to https://github.com/llvm/circt/ ! :-)

### ISSUE THREAD

**Issue by lattner** [llvm/circt#960]
The top level web page has pointers to the forum and other places, but doesn't point to the GitHub code.  Could this get added please?  @drom 

-Chris

**Comment by teqdruid** [comment]
There's a "github" link in the drop-down under "source", along with the doxygen link. It'd be convenient if it wasn't hidden under a drop down menu, though.

**Comment by lattner** [comment]
Ah, that's nice, but not very obvious.  It would be great if it were in the middle of the page so you don't have to disclose anything to get to it.

**Comment by xgupta** [comment]
I have also given the admin role to @drom.
But I am surprised that linking a GitHub issue link in a commit can also close the issue.
